# A2 passages (p0021-p0040); format as a1.py
P = []

P.append(dict(title="رحلة إلى الجبل", names=["سمير"], s=[
    ("في الأسبوع الماضي قررت أن أذهب مع صديقي سمير في رحلة إلى الجبل.",
     "Last week I decided to go on a trip to the mountain with my friend Samir."),
    ("خرجنا من المدينة في الصباح بالسيارة.", "We left the city in the morning by car."),
    ("كان الطريق طويلا، لكن الجو كان جميلا.", "The road was long, but the weather was lovely."),
    ("بعد ثلاث ساعات وصلنا إلى قرية صغيرة تحت الجبل.", "After three hours we reached a small village below the mountain."),
    ("هناك تركنا السيارة وبدأنا نمشي.", "There we left the car and started walking."),
    ("في الطريق رأينا أشجارا كثيرة وحيوانات صغيرة.", "On the way we saw many trees and small animals."),
    ("بعد ساعتين لم أعد أستطيع أن أمشي، فجلسنا تحت شجرة كبيرة.", "After two hours I couldn't walk any more, so we sat under a big tree."),
    ("أكلنا الخبز والجبن، وشربنا الماء البارد.", "We ate bread and cheese, and drank cold water."),
    ("ثم مشينا حتى وصلنا إلى أعلى الجبل.", "Then we walked until we reached the top of the mountain."),
    ("من هناك كانت القرية صغيرة جدا، والسماء زرقاء.", "From there the village was very small, and the sky was blue."),
    ("أخذ سمير صورا كثيرة بهاتفه.", "Samir took a lot of pictures with his phone."),
    ("في المساء عدنا إلى المدينة، وكنا سعداء جدا.", "In the evening we went back to the city, and we were very happy."),
    ("قال سمير إننا سنذهب مرة أخرى في الربيع.", "Samir said we will go again in the spring."),
], q=[
    ("mc", "كيف ذهب الكاتب وسمير إلى القرية؟", "How did the writer and Samir get to the village?",
     ["في سيارة", "في حافلة", "في قطار", "في طائرة"], ["سيارة"], 1),
    ("tf", "كان الجو سيئا في ذلك اليوم.", "The weather was bad that day.", False, ["جو", "جميل"], 2),
    ("mc", "لماذا جلس الصديقان تحت الشجرة؟", "Why did the two friends sit under the tree?",
     ["لأن الكاتب لم يستطع أن يمشي", "لأن المطر بدأ والجو صار باردا", "لأن سمير كان جائعا", "لأن الطريق انتهى"], ["جلس", "شجرة"], 6),
    ("tf", "أخذ سمير صورا بهاتفه.", "Samir took pictures with his phone.", True, ["صورة", "هاتف"], 10),
    ("mc", "متى يريد سمير أن يعود إلى الجبل؟", "When does Samir want to go back to the mountain?",
     ["بعد الشتاء", "في الصيف القادم", "في الشتاء", "في الخريف"], ["ربيع"], 12),
]))

P.append(dict(title="عند الطبيب", names=["هدى"], s=[
    ("منذ يومين تشعر هدى بألم في رأسها.", "For two days Huda has had a pain in her head."),
    ("أولا ظنت أن الألم بسبب النوم القليل.", "At first she thought the pain was because of too little sleep."),
    ("لكن الألم لم يتوقف، فقررت أن تذهب إلى الطبيب.", "But the pain did not stop, so she decided to go to the doctor."),
    ("في المستشفى انتظرت ساعة كاملة، لأن الناس كانوا كثيرين.", "At the hospital she waited a whole hour, because there were many people."),
    ("سألها الطبيب: متى بدأ الألم؟ وهل تنامين جيدا؟", "The doctor asked her: When did the pain start? And do you sleep well?"),
    ("قالت هدى إنها تعمل على الحاسوب حتى وقت متأخر كل ليلة.", "Huda said she works on the computer until late every night."),
    ("قال الطبيب إن المرض ليس خطيرا.", "The doctor said the illness is not serious."),
    ("ثم أعطاها دواء وقال لها: يجب أن تنامي ثماني ساعات كل ليلة.",
     "Then he gave her medicine and said to her: You must sleep eight hours every night."),
    ("وقال أيضا إن عليها أن تشرب الماء كثيرا وتمشي قليلا كل يوم.", "He also said she should drink a lot of water and walk a little every day."),
    ("بعد أسبوع شعرت هدى أنها أفضل بكثير.", "After a week Huda felt much better."),
    ("الآن تغلق الحاسوب في الساعة 10 وتقرأ كتابا قبل النوم.", "Now she turns off the computer at 10 o'clock and reads a book before sleeping."),
], q=[
    ("tf", "ذهبت هدى إلى الطبيب في اليوم الأول.", "Huda went to the doctor on the first day.", False, ["طبيب", "قرر"], 2),
    ("mc", "كم انتظرت هدى في المستشفى؟", "How long did Huda wait at the hospital?",
     ["ستين دقيقة", "عشر دقائق", "يوما", "أسبوعا"], ["انتظر", "ساعة"], 3),
    ("mc", "ما سبب الألم؟", "What was the cause of the pain?",
     ["العمل على الحاسوب في الليل", "شرب القهوة الكثيرة في الليل", "الماء البارد", "الشمس"], ["حاسوب"], 5),
    ("tf", "قال الطبيب إن المرض خطير.", "The doctor said the illness was serious.", False, ["خطير", "مرض"], 6),
    ("tf", "هدى الآن تقرأ قبل أن تنام.", "Huda now reads before she sleeps.", True, ["قرأ", "نوم"], 10),
]))

P.append(dict(title="مقابلة عمل", names=["فراس"], s=[
    ("فراس شاب عمره خمسة وعشرون عاما.", "Firas is a young man of twenty-five."),
    ("أنهى دراسته في الجامعة قبل سنة، ومنذ ذلك الوقت يبحث عن عمل.",
     "He finished his studies at university a year ago, and since then he has been looking for a job."),
    ("أرسل رسائل إلى شركات كثيرة، لكن لم يتصل به أحد.", "He sent letters to many companies, but nobody called him."),
    ("أمس وصلته رسالة من شركة كبيرة تطلب منه أن يأتي إلى مقابلة.",
     "Yesterday he got a letter from a big company asking him to come to an interview."),
    ("كان فراس سعيدا جدا، لكنه كان قلقا أيضا.", "Firas was very happy, but he was also worried."),
    ("في المساء اشترى قميصا جديدا، وقرأ كثيرا عن الشركة.", "In the evening he bought a new shirt and read a lot about the company."),
    ("في يوم المقابلة وصل قبل الموعد بنصف ساعة.", "On the day of the interview he arrived half an hour before the appointment."),
    ("تكلم المدير معه عن دراسته وخططه للمستقبل.", "The manager talked with him about his studies and his plans for the future."),
    ("تكلم فراس بشكل جيد، ولم يكن خائفا.", "Firas spoke well, and he was not afraid."),
    ("في النهاية قال المدير: سنتصل بك في الأسبوع القادم.", "At the end the manager said: We will call you next week."),
    ("بعد خمسة أيام اتصل المدير بفراس.", "Five days later the manager called Firas."),
    ("قال له إنه حصل على الوظيفة، وإنه سيبدأ العمل في بداية الشهر!",
     "He told him he had got the job, and that he would start work at the beginning of the month!"),
], q=[
    ("tf", "اتصلت شركات كثيرة بفراس بعد الجامعة.", "Many companies called Firas after university.", False, ["اتصل", "شركة"], 2),
    ("mc", "ماذا فعل فراس في المساء قبل المقابلة؟", "What did Firas do the evening before the interview?",
     ["اشترى ملابس", "ذهب إلى البحر", "نام في الساعة 8", "اتصل بالمدير"], ["اشترى", "قميص"], 5),
    ("mc", "متى وصل فراس إلى المقابلة؟", "When did Firas arrive at the interview?",
     ["قبل موعده بثلاثين دقيقة", "متأخرا عن موعده بساعة كاملة", "في الوقت تماما", "في المساء"], ["موعد"], 6),
    ("tf", "حصل فراس على الوظيفة.", "Firas got the job.", True, ["حصل", "وظيفة"], 11),
]))

P.append(dict(title="المباراة الكبيرة", names=["رامي"], s=[
    ("يوم السبت كانت هناك مباراة كرة قدم مهمة في مدينتنا.", "On Saturday there was an important football match in our city."),
    ("الفريق الذي يلعب فيه أخي رامي كان يلعب ضد فريق قوي من العاصمة.",
     "The team my brother Rami plays for was playing against a strong team from the capital."),
    ("ذهبت مع أبي قبل بداية المباراة بساعة.", "I went with my father an hour before the start of the match."),
    ("كان هناك جمهور كبير، وكان الناس سعداء.", "There was a big crowd, and people were happy."),
    ("في الدقائق الأولى سجل الفريق الآخر هدفا.", "In the first minutes the other team scored a goal."),
    ("كان أبي حزينا، وقال: هذا الفريق أفضل منا.", "My father was sad, and said: This team is better than us."),
    ("لكن قبل نهاية الساعة الأولى سجل رامي هدفا جميلا.", "But before the end of the first hour Rami scored a beautiful goal."),
    ("بعد ذلك لعب فريقنا بشكل أفضل.", "After that our team played better."),
    ("قبل النهاية بخمس دقائق سجلنا الهدف الثاني.", "Five minutes before the end we scored the second goal."),
    ("فاز فريقنا، وكان الجمهور سعيدا جدا.", "Our team won, and the crowd was very happy."),
    ("بعد المباراة انتظرنا رامي خارج المكان.", "After the match we waited for Rami outside."),
    ("ثم ذهبنا كلنا إلى مطعم وأكلنا اللحم والرز.", "Then we all went to a restaurant and ate meat and rice."),
], q=[
    ("mc", "من أين جاء الفريق الآخر؟", "Where did the other team come from?",
     ["من عاصمة البلد", "من قرية صغيرة", "من مدينة الكاتب", "من بلد آخر"], ["فريق"], 1),
    ("tf", "سجل فريق رامي الهدف الأول في المباراة.", "Rami's team scored the first goal of the match.", False, ["هدف"], 4),
    ("tf", "فاز فريق رامي في النهاية.", "Rami's team won in the end.", True, ["فاز", "فريق"], 9),
    ("mc", "أين انتظر الكاتب وأبوه رامي؟", "Where did the writer and his father wait for Rami?",
     ["خارج مكان المباراة", "في المطعم", "في البيت", "في السيارة بعد المباراة"], ["انتظر"], 10),
]))

P.append(dict(title="زواج أخي", names=["زياد", "سلمى"], s=[
    ("في الشهر الماضي تزوج أخي الكبير زياد.", "Last month my older brother Ziad got married."),
    ("زوجته اسمها سلمى، وهي تعمل معلمة في مدرسة قريبة من بيتنا.",
     "His wife is called Salma, and she works as a teacher at a school near our house."),
    ("قبل الحفلة بأسبوع كان في البيت ناس كثيرون.", "A week before the party there were many people in the house."),
    ("جاء أفراد العائلة من مدن بعيدة.", "Members of the family came from distant cities."),
    ("كانت أمي تعمل في المطبخ من الصباح حتى الليل.", "My mother worked in the kitchen from morning until night."),
    ("أنا ساعدت أبي في شراء الطعام والفاكهة.", "I helped my father buy the food and fruit."),
    ("كانت الحفلة في فندق كبير في وسط المدينة.", "The party was in a big hotel in the centre of the city."),
    ("كانت سلمى جميلة جدا في ملابسها البيضاء.", "Salma was very beautiful in her white clothes."),
    ("بقي الناس في الحفلة حتى الساعة الثانية بعد منتصف الليل.", "People stayed at the party until two o'clock after midnight."),
    ("كانت جدتي سعيدة أكثر من كل الناس.", "My grandmother was happier than everyone."),
    ("الآن يسكن زياد وسلمى في شقة صغيرة قريبة منا.", "Now Ziad and Salma live in a small flat near us."),
    ("يأتيان إلينا كل يوم جمعة ونتناول الغداء معا.", "They come to us every Friday and we have lunch together."),
], q=[
    ("mc", "ماذا تعمل سلمى؟", "What does Salma do?",
     ["تعلم الأطفال", "تعمل في فندق", "تعمل في مستشفى", "لا تعمل"], ["معلم"], 1),
    ("tf", "كانت الحفلة في بيت العائلة.", "The party was at the family home.", False, ["حفلة", "فندق"], 6),
    ("mc", "ما لون ملابس سلمى في الحفلة؟", "What colour were Salma's clothes at the party?",
     ["أبيض", "أسود", "أحمر", "أزرق"], ["ملبس"], 7),
    ("tf", "يسكن زياد وسلمى الآن قريبا من العائلة.", "Ziad and Salma now live near the family.", True, ["سكن", "قريب"], 10),
    ("tf", "ساعد الكاتب أمه في المطبخ.", "The writer helped his mother in the kitchen.", False, ["ساعد", "أب"], 5),
]))

P.append(dict(title="نبحث عن شقة", names=["نادية"], s=[
    ("أعمل الآن في مدينة جديدة، ولذلك أبحث عن شقة.", "I now work in a new city, so I am looking for a flat."),
    ("صديقتي في العمل نادية أعطتني رقم رجل عنده شقق كثيرة.", "My friend at work, Nadia, gave me the number of a man who has many flats."),
    ("اتصلت به، وذهبنا معا لنرى ثلاث شقق.", "I called him, and we went together to see three flats."),
    ("الشقة الأولى كانت كبيرة وجميلة، لكنها غالية جدا.", "The first flat was big and beautiful, but very expensive."),
    ("الشقة الثانية كانت رخيصة، لكنها بعيدة عن مكان عملي.", "The second flat was cheap, but far from my workplace."),
    ("وكانت أيضا قديمة، والمطبخ فيها صغير جدا.", "It was also old, and its kitchen was very small."),
    ("أما الشقة الثالثة فكانت في شارع صغير ليس فيه سيارات كثيرة.",
     "As for the third flat, it was on a small street without many cars."),
    ("فيها غرفتان وحمام ومطبخ جديد.", "It has two rooms, a bathroom and a new kitchen."),
    ("من النافذة أرى حديقة كبيرة.", "From the window I see a big park."),
    ("سعرها مناسب، وهي قريبة من محطة الحافلات.", "Its price is reasonable, and it is near the bus station."),
    ("قررت أن آخذ الشقة الثالثة.", "I decided to take the third flat."),
    ("سأبدأ أسكن فيها في بداية الشهر القادم.", "I will start living in it at the beginning of next month."),
    ("نادية سعيدة، لأن الشقة قريبة من بيتها أيضا.", "Nadia is happy, because the flat is also near her house."),
], q=[
    ("tf", "كانت الشقة الأولى رخيصة.", "The first flat was cheap.", False, ["شقة", "غال"], 3),
    ("mc", "ما المشكلة في الشقة الثانية؟", "What was the problem with the second flat?",
     ["ليست قريبة من عمل الكاتب", "سعرها كبير جدا", "في شارع فيه سيارات كثيرة", "ليس فيها مطبخ"], ["بعيد"], 4),
    ("mc", "ماذا يرى الكاتب من نافذة الشقة الثالثة؟", "What does the writer see from the third flat's window?",
     ["حديقة", "البحر", "محطة القطار", "مدرسة"], ["نافذة"], 8),
    ("tf", "الشقة الثالثة قريبة من محطة الحافلات.", "The third flat is near the bus station.", True, ["محطة", "قريب"], 9),
    ("mc", "متى سيبدأ الكاتب يسكن في الشقة؟", "When will the writer start living in the flat?",
     ["في أول الشهر القادم", "غدا", "بعد سنة", "في نهاية الأسبوع القادم"], ["شهر", "بداية"], 11),
]))

P.append(dict(title="رسالة من كندا", names=["كندا", "سعاد", "تورنتو"], s=[
    ("عزيزتي سعاد،", "Dear Suad,"),
    ("وصلت إلى كندا منذ شهرين، وأنا بخير والحمد لله.", "I arrived in Canada two months ago, and I am well, thank God."),
    ("أسكن الآن في تورنتو، وهي مدينة كبيرة فيها ناس من كل العالم.",
     "I now live in Toronto, which is a big city with people from all over the world."),
    ("الجو هنا بارد جدا، وفي الشتاء لا نرى الشمس كثيرا.", "The weather here is very cold, and in winter we don't see the sun much."),
    ("أولا كان الأمر صعبا، لأني لم أكن أعرف أحدا.", "At first it was hard, because I didn't know anyone."),
    ("لكني الآن أدرس الإنجليزية في مدرسة للكبار، وعندي أصدقاء من بلاد مختلفة.",
     "But now I study English at a school for adults, and I have friends from different countries."),
    ("وجدت أيضا عملا في مطعم عربي قريب من بيتي.", "I also found a job in an Arab restaurant near my home."),
    ("العمل صعب، لكن صاحب المطعم رجل طيب.", "The work is hard, but the owner of the restaurant is a kind man."),
    ("أفكر في أسرتي كثيرا، وفي طعام أمي.", "I think about my family a lot, and about my mother's food."),
    ("كل أسبوع أتكلم معهم على الإنترنت.", "Every week I talk to them on the internet."),
    ("كيف حالك أنت؟ وكيف العمل في المدرسة؟", "How are you? And how is work at the school?"),
    ("اكتبي لي عن كل شيء.", "Write to me about everything."),
], q=[
    ("mc", "منذ متى الكاتبة في كندا؟", "How long has the writer been in Canada?",
     ["منذ ستين يوما", "منذ سنة", "منذ أسبوعين", "منذ ثلاث سنوات"], ["منذ", "شهر"], 1),
    ("tf", "الجو في تورنتو حار.", "The weather in Toronto is hot.", False, ["جو", "بارد"], 3),
    ("mc", "أين تعمل الكاتبة؟", "Where does the writer work?",
     ["في مكان للطعام", "في مدرسة", "في مستشفى", "في شركة"], ["عمل", "مطعم"], 6),
    ("tf", "تتكلم الكاتبة مع أسرتها كل أسبوع.", "The writer talks with her family every week.", True, ["تكلم", "أسبوع"], 9),
]))

P.append(dict(title="في السوق القديم", names=[], s=[
    ("في مدينتنا سوق قديم عمره أكثر من 300 سنة.", "In our city there is an old market more than 300 years old."),
    ("شوارع السوق صغيرة، وفيها دكاكين كثيرة.", "The market's streets are small, and there are many shops in them."),
    ("في كل شارع يبيع الناس شيئا مختلفا.", "In each street people sell something different."),
    ("في الشارع الأول يبيعون الملابس والأحذية.", "In the first street they sell clothes and shoes."),
    ("وفي الشارع الثاني يبيعون الذهب.", "And in the second street they sell gold."),
    ("أنا أحب شارع الشاي والقهوة أكثر من كل الشوارع، لأن رائحته جميلة.",
     "I like the tea and coffee street more than all the streets, because it smells lovely."),
    ("الناس يأتون إلى السوق من كل العالم ليأخذوا صورا ويشتروا الهدايا.",
     "People come to the market from all over the world to take pictures and buy presents."),
    ("في السوق لا تدفع السعر الأول أبدا.", "In the market you never pay the first price."),
    ("صاحب الدكان يقول رقما كبيرا، ثم تقول أنت رقما صغيرا، وفي النهاية تتفقان.",
     "The shopkeeper says a big number, then you say a small number, and in the end you agree."),
    ("أمس اشتريت من هناك حقيبة جميلة لأختي.", "Yesterday I bought a beautiful bag there for my sister."),
    ("كان السعر الأول مئة دولار، لكني دفعت ستين فقط.", "The first price was a hundred dollars, but I paid only sixty."),
    ("أختي أحبت الحقيبة كثيرا.", "My sister loved the bag very much."),
], q=[
    ("tf", "شوارع السوق كبيرة.", "The market's streets are big.", False, ["شارع", "سوق"], 1),
    ("mc", "ماذا يبيعون في الشارع الثاني؟", "What do they sell in the second street?",
     ["ذهبا", "ملابس", "شايا", "أحذية"], ["باع"], 4),
    ("mc", "لماذا يحب الكاتب شارع الشاي والقهوة؟", "Why does the writer like the tea and coffee street?",
     ["بسبب رائحته", "لأنه قريب من البيت", "لأن الأسعار رخيصة", "لأن صديقه يعمل هناك"], ["رائحة"], 5),
    ("tf", "دفع الكاتب أقل من السعر الأول.", "The writer paid less than the first price.", True, ["دفع", "سعر"], 10),
]))

P.append(dict(title="أتعلم الطعام", names=[], s=[
    ("عندما كنت أسكن مع أسرتي، كانت أمي تعمل كل الطعام.", "When I lived with my family, my mother made all the food."),
    ("لكن الآن أسكن في مدينة أخرى، ولذلك يجب أن أتعلم.", "But now I live in another city, so I have to learn."),
    ("أولا كنت آكل في المطاعم كل يوم.", "At first I ate in restaurants every day."),
    ("لكن الطعام في المطاعم غال، وليس جيدا للصحة دائما.", "But restaurant food is expensive, and not always good for your health."),
    ("لذلك قررت أن أتصل بأمي كل مساء لتعلمني طبقا جديدا.", "So I decided to call my mother every evening so she could teach me a new dish."),
    ("أول طبق تعلمته كان الرز مع اللحم.", "The first dish I learned was rice with meat."),
    ("في المرة الأولى نسيت الطعام على النار، ولم أستطع أن آكله.", "The first time I forgot the food on the fire, and I couldn't eat it."),
    ("في المرة الثانية كان الطعام أفضل قليلا.", "The second time the food was a little better."),
    ("الآن أعرف أن أعمل خمسة أطباق أو ستة.", "Now I know how to make five or six dishes."),
    ("في الأسبوع الماضي دعوت أصدقائي إلى العشاء.", "Last week I invited my friends to dinner."),
    ("أكلوا كل شيء، وقالوا إن الطعام كان ممتازا.", "They ate everything, and said the food was excellent."),
    ("أمي سعيدة جدا، وتقول إنها ستأتي لتأكل عندي.", "My mother is very happy, and she says she will come to eat at my place."),
], q=[
    ("tf", "كانت أم الكاتب تعمل الطعام عندما كان يسكن مع أسرته.", "The writer's mother made the food when he lived with his family.",
     True, ["أم", "طعام"], 0),
    ("mc", "لماذا لم يستمر الكاتب في الأكل في المطاعم؟", "Why didn't the writer keep eating in restaurants?",
     ["لأن طعامها ليس رخيصا", "لأن المطاعم بعيدة عن البيت", "لأن أمه غضبت", "لأنه لا يحب اللحم"], ["مطعم", "غال"], 3),
    ("mc", "ما أول طبق تعلمه الكاتب؟", "What was the first dish the writer learned?",
     ["رز ولحم", "سمك وخبز", "جبن وخبز", "فاكهة وحليب"], ["طبق", "تعلم"], 5),
    ("tf", "كان الطبق الأول ممتازا.", "The first dish was excellent.", False, ["أول", "نسي"], 6),
    ("tf", "أحب الأصدقاء طعام الكاتب.", "The friends liked the writer's food.", True, ["صديق", "دعا"], 9),
]))

P.append(dict(title="يوم ممطر", names=["وليد"], s=[
    ("صباح أمس كان المطر شديدا جدا.", "Yesterday morning the rain was very heavy."),
    ("خرج وليد من البيت متأخرا، لأنه لم يسمع صوت الساعة.", "Walid left home late, because he didn't hear the alarm."),
    ("دخل سيارته بسرعة وأخذ الطريق إلى عمله.", "He got into his car quickly and took the road to work."),
    ("كان الماء في كل الشوارع، والسيارات لا تمشي بسرعة.", "There was water in all the streets, and the cars were not moving fast."),
    ("في الطريق توقفت السيارة التي أمامه، ولم يستطع وليد أن يوقف سيارته.",
     "On the way the car in front of him stopped, and Walid could not stop his car."),
    ("ضربت سيارته السيارة الأخرى من الخلف.", "His car hit the other car from behind."),
    ("لم يصب أحد، والحمد لله.", "Nobody was hurt, thank God."),
    ("خرج صاحب السيارة الأخرى، وكان رجلا كبيرا في السن.", "The owner of the other car got out, and he was an old man."),
    ("قال له وليد: أنا آسف جدا، هذا خطئي.", "Walid said to him: I'm very sorry, this is my fault."),
    ("بعد قليل جاءت الشرطة وكتبت تقريرا.", "After a while the police came and wrote a report."),
    ("وصل وليد إلى العمل بعد ساعتين.", "Walid arrived at work two hours later."),
    ("قال له المدير: الحمد لله أنك بخير.", "The manager said to him: Thank God you are all right."),
    ("في المساء أخذ وليد سيارته إلى رجل يعمل في السيارات.", "In the evening Walid took his car to a man who works on cars."),
], q=[
    ("mc", "لماذا خرج وليد متأخرا؟", "Why did Walid leave late?",
     ["لأنه لم يسمع الساعة", "كان مريضا", "لم تعمل سيارته", "كان ينتظر صديقه في الشارع"], ["سمع", "ساعة"], 1),
    ("tf", "كانت السيارات تمشي بسرعة ذلك الصباح.", "The cars were moving fast that morning.", False, ["سيارة", "بسرعة"], 3),
    ("tf", "لم يصب أحد في الحادث.", "Nobody was hurt in the accident.", True, ["أصاب", "أحد"], 6),
    ("mc", "من كتب التقرير؟", "Who wrote the report?",
     ["رجال الشرطة", "وليد", "الرجل الكبير", "المدير"], ["تقرير", "شرطة"], 9),
]))

P.append(dict(title="بيت الكتب", names=["سليم"], s=[
    ("في حينا بيت كتب صغير قريب من السوق.", "In our neighbourhood there is a small house of books near the market."),
    ("كنت أذهب إليه مع أبي عندما كنت طفلا.", "I used to go there with my father when I was a child."),
    ("فيه آلاف الكتب بالعربية والإنجليزية والفرنسية.", "It has thousands of books in Arabic, English and French."),
    ("هناك غرفة خاصة للأطفال، فيها كتب جميلة وكراس صغيرة.", "There is a special room for children, with lovely books and small chairs."),
    ("المكان مفتوح كل يوم من الساعة 9 حتى الساعة 8 مساء، إلا يوم الجمعة.",
     "The place is open every day from 9 until 8 in the evening, except Friday."),
    ("تستطيع أن تأخذ ثلاثة كتب إلى البيت مدة أسبوعين.", "You can take three books home for two weeks."),
    ("الآن أذهب إليه كل يوم سبت لأقرأ وأدرس.", "Now I go there every Saturday to read and study."),
    ("لا أحد يتكلم بصوت عال هناك، والكل يقرأ.", "Nobody talks loudly there, and everyone reads."),
    ("المسؤول عن المكان رجل لطيف اسمه سليم.", "The man in charge of the place is a kind man called Salim."),
    ("هو يعرف كل كتاب هناك، ويساعد الطلاب دائما.", "He knows every book there, and always helps students."),
    ("في الشهر القادم سيبدأ برنامجا لتعليم الكبار القراءة.", "Next month he will start a programme to teach adults to read."),
], q=[
    ("tf", "المكان مفتوح يوم الجمعة.", "The place is open on Friday.", False, ["مفتوح", "الجمعة"], 4),
    ("mc", "كم كتابا تستطيع أن تأخذ إلى البيت؟", "How many books can you take home?",
     ["ثلاثة", "خمسة", "كتابا واحدا", "عشرة"], ["كتاب"], 5),
    ("mc", "متى يذهب الكاتب إلى بيت الكتب الآن؟", "When does the writer go to the house of books now?",
     ["مرة في الأسبوع", "كل يوم", "كل يوم جمعة", "مرة في الشهر"], ["ذهب"], 6),
    ("tf", "سليم يساعد الطلاب.", "Salim helps the students.", True, ["ساعد", "طالب"], 9),
]))

P.append(dict(title="الصحة كل يوم", names=[], s=[
    ("يقول الأطباء إننا يجب أن نمشي كل يوم، لأن هذا مهم جدا للصحة.", "Doctors say we should walk every day, because this is very important for health."),
    ("لكن كثيرا من الناس لا يجدون وقتا له.", "But many people don't find time for it."),
    ("هم يعملون ساعات طويلة، ثم يعودون إلى البيت ويجلسون أمام التلفاز.",
     "They work long hours, then come home and sit in front of the TV."),
    ("في الحقيقة لا نحتاج إلى وقت كبير.", "In fact, we don't need a lot of time."),
    ("نصف ساعة كل يوم يكفي.", "Half an hour every day is enough."),
    ("تستطيع أن تمشي إلى عملك بدلا من أن تأخذ السيارة.", "You can walk to work instead of taking the car."),
    ("أو تستطيع أن تمشي مع أصدقائك في الحديقة بعد العمل.", "Or you can walk with your friends in the park after work."),
    ("عندما نمشي كل يوم، يكون القلب أحسن، وننام جيدا.", "When we walk every day, the heart is better, and we sleep well."),
    ("وهو أيضا يجعلنا سعداء.", "It also makes us happy."),
    ("ويجب أيضا أن نأكل طعاما جيدا ونشرب الماء كثيرا.", "We should also eat good food and drink a lot of water."),
    ("الفاكهة أفضل من الحلوى، والماء أفضل من القهوة.", "Fruit is better than sweets, and water is better than coffee."),
    ("ابدأ اليوم، ولا تنتظر حتى الغد!", "Start today, and don't wait until tomorrow!"),
], q=[
    ("mc", "كم دقيقة يكفي أن نمشي كل يوم؟", "How many minutes a day is it enough to walk?",
     ["ثلاثون دقيقة", "عشر دقائق", "ساعتان", "خمس دقائق"], ["كفى"], 4),
    ("tf", "يقول الكاتب إننا نحتاج إلى وقت كبير.", "The writer says we need a lot of time.", False, ["احتاج", "وقت"], 3),
    ("mc", "ماذا يمكن أن تفعل بدلا من أخذ السيارة؟", "What can you do instead of taking the car?",
     ["أن تذهب إلى العمل على قدميك", "أن تأخذ الحافلة كل صباح إلى العمل", "أن تبقى في البيت", "أن تنام أكثر"], ["سيارة", "بدلا من"], 5),
    ("tf", "إذا مشينا، ننام بشكل أفضل.", "If we walk, we sleep better.", True, ["مشى", "نام"], 7),
]))

P.append(dict(title="قرية جدي", names=[], s=[
    ("كل صيف أقضي أسبوعين في قرية جدي.", "Every summer I spend two weeks in my grandfather's village."),
    ("القرية صغيرة، وعدد الناس فيها أقل من ألف.", "The village is small, and there are fewer than a thousand people in it."),
    ("البيوت فيها قديمة، وحول كل بيت أشجار وحيوانات.", "The houses there are old, and around each house there are trees and animals."),
    ("جدي عنده حيوانات كثيرة، وأنا أعطيها الطعام كل صباح.", "My grandfather has many animals, and I give them food every morning."),
    ("بعد ذلك أساعده في العمل في الأرض.", "After that I help him work the land."),
    ("نشرب الحليب في الصباح، ونأكل الخبز الذي تعمله جدتي.", "We drink milk in the morning, and eat the bread my grandmother makes."),
    ("في القرية لا يوجد إنترنت، والهاتف لا يعمل جيدا.", "In the village there is no internet, and the phone doesn't work well."),
    ("أولا كان هذا صعبا علي.", "At first this was hard for me."),
    ("لكن الآن أحب الحياة هناك، لأنها بسيطة وجميلة.", "But now I love life there, because it is simple and beautiful."),
    ("في المساء يجلس الناس أمام البيوت ويتكلمون.", "In the evening people sit in front of the houses and talk."),
    ("السماء في الليل جميلة جدا، وفيها نجوم كثيرة.", "The sky at night is very beautiful, with many stars."),
    ("عندما أعود إلى المدينة، أفكر في القرية دائما.", "When I go back to the city, I always think about the village."),
    ("أريد أن أسكن هناك عندما أكبر.", "I want to live there when I grow up."),
], q=[
    ("mc", "كم يوما يقضي الكاتب في القرية؟", "How many days does the writer spend in the village?",
     ["أربعة عشر يوما", "سبعة أيام", "ثلاثين يوما", "ثلاثة أيام"], ["قضى"], 0),
    ("tf", "القرية كبيرة وفيها ناس كثيرون.", "The village is big and has many people.", False, ["قرية", "صغير"], 1),
    ("mc", "ماذا يفعل الكاتب بعد أن يعطي الحيوانات الطعام؟", "What does the writer do after feeding the animals?",
     ["يعمل مع جده", "يلعب مع الأطفال", "يذهب إلى السوق", "ينام حتى الظهر"], ["ساعد"], 4),
    ("tf", "الإنترنت في القرية جيد.", "The internet in the village is good.", False, ["إنترنت"], 6),
    ("tf", "يحب الكاتب الآن الحياة في القرية.", "The writer now loves life in the village.", True, ["أحب", "حياة"], 8),
]))

P.append(dict(title="في المطار", names=["دبي", "باريس"], s=[
    ("كانت هذه أول مرة أذهب فيها بالطائرة بدون أسرتي.", "This was the first time I went by plane without my family."),
    ("وصلت إلى المطار قبل الرحلة بثلاث ساعات، لأني كنت خائفا من التأخر.",
     "I arrived at the airport three hours before the flight, because I was afraid of being late."),
    ("في المطار ناس كثيرون من بلاد مختلفة.", "At the airport there are many people from different countries."),
    ("أعطيت أوراقي للموظف، ووضعت حقيبتي الكبيرة أمامه.", "I gave my papers to the employee, and put my big bag in front of him."),
    ("قال الموظف إن الحقيبة كبيرة قليلا، لكن لا بأس.", "The employee said the bag was a little big, but it was fine."),
    ("ثم انتظرت في مطعم صغير وشربت القهوة.", "Then I waited in a small restaurant and drank coffee."),
    ("قبل الرحلة بساعة سمعت إعلانا: الرحلة إلى دبي متأخرة ساعتين.",
     "An hour before the flight I heard an announcement: the flight to Dubai is two hours late."),
    ("قرأت كتابا وتكلمت مع امرأة من باريس.", "I read a book and talked with a woman from Paris."),
    ("كانت لطيفة جدا، وقالت إنها تعمل في شركة في دبي.", "She was very nice, and said she works for a company in Dubai."),
    ("في النهاية دخلنا الطائرة.", "In the end we got on the plane."),
    ("كان مقعدي بجانب النافذة، فرأيت المدينة من السماء.", "My seat was next to the window, so I saw the city from the sky."),
    ("وصلنا إلى دبي في منتصف الليل.", "We arrived in Dubai in the middle of the night."),
], q=[
    ("tf", "كانت أسرة الكاتب معه في الطائرة.", "The writer's family was with him on the plane.", False, ["أسرة", "طائرة"], 0),
    ("mc", "لماذا وصل الكاتب إلى المطار قبل الرحلة بوقت طويل؟", "Why did the writer arrive at the airport long before the flight?",
     ["لأنه لم يرد أن يتأخر", "لأنه كان يريد أن يأكل", "لأنه كان ينتظر صديقه", "لأنه نسي الموعد"], ["خائف", "تأخر"], 1),
    ("mc", "كم ساعة تأخرت الرحلة؟", "How many hours was the flight delayed?",
     ["ساعتين", "ثلاث ساعات", "ساعة واحدة", "نصف ساعة"], ["رحلة", "ساعة"], 6),
    ("tf", "كان مقعد الكاتب بجانب النافذة.", "The writer's seat was next to the window.", True, ["مقعد", "نافذة"], 10),
]))

P.append(dict(title="حديقة الحيوان", names=["أفريقيا"], s=[
    ("يوم الجمعة أخذنا أبي إلى حديقة الحيوان.", "On Friday my father took us to the zoo."),
    ("الحديقة كبيرة جدا، وفيها حيوانات من كل العالم.", "The zoo is very big, and it has animals from all over the world."),
    ("أولا رأينا الأسود.", "First we saw the lions."),
    ("كان الأسد الكبير ينام تحت شجرة، والصغار يلعبون حوله.", "The big lion was sleeping under a tree, and the cubs were playing around it."),
    ("ثم رأينا حيوانات كبيرة جدا من أفريقيا.", "Then we saw very big animals from Africa."),
    ("أختي الصغيرة أعطت واحدا منها تفاحة، فأكلها بسرعة.", "My little sister gave one of them an apple, and it ate it quickly."),
    ("بعد ذلك رأينا حيوانات صغيرة تلعب على الأشجار، وكانت جميلة جدا.",
     "After that we saw small animals playing in the trees, and they were very lovely."),
    ("في الظهر تناولنا الغداء في مطعم داخل الحديقة.", "At noon we had lunch in a restaurant inside the zoo."),
    ("بعد الغداء رأينا السمك في الماء.", "After lunch we saw the fish in the water."),
    ("كان هناك سمك بألوان جميلة: أحمر وأصفر وأزرق.", "There were fish in beautiful colours: red, yellow and blue."),
    ("في طريق العودة نامت أختي في السيارة.", "On the way back my sister fell asleep in the car."),
    ("قالت أمي إنها ستأخذنا مرة أخرى في الصيف.", "My mother said she would take us again in the summer."),
    ("أنا أريد أن أعمل في حديقة الحيوان عندما أكبر.", "I want to work at the zoo when I grow up."),
], q=[
    ("mc", "ماذا كان يفعل الأسد الكبير؟", "What was the big lion doing?",
     ["كان ينام", "كان يأكل", "كان يلعب", "كان يشرب"], ["أسد"], 3),
    ("tf", "أعطت الأخت الحيوان خبزا.", "The sister gave the animal bread.", False, ["أعطى", "تفاح"], 5),
    ("mc", "أين تناولت الأسرة الغداء؟", "Where did the family have lunch?",
     ["داخل حديقة الحيوان", "في البيت", "في السيارة", "عند جدتها في القرية"], ["تناول", "غداء"], 7),
    ("tf", "يريد الكاتب أن يعمل مع الحيوانات.", "The writer wants to work with animals.", True, ["أراد", "عمل"], 12),
]))

P.append(dict(title="أول يوم في الجامعة", names=["رنا"], s=[
    ("اليوم كان أول يوم لي في الجامعة.", "Today was my first day at university."),
    ("قمت من سريري في الساعة 5، لأني كنت قلقة.", "I got out of bed at 5 o'clock, because I was worried."),
    ("الجامعة كبيرة، وفيها مبان كثيرة، ولم أعرف أين أذهب.", "The university is big, with many buildings, and I didn't know where to go."),
    ("سألت طالبة أين كلية الطب، فأخذتني إلى هناك.", "I asked a student where the medical school was, and she took me there."),
    ("اسمها رنا، وهي تدرس في السنة الثالثة.", "Her name is Rana, and she is in her third year."),
    ("قالت لي إن السنة الأولى صعبة، لكنها جميلة.", "She told me the first year is hard, but lovely."),
    ("الدرس الأول كان في غرفة كبيرة فيها أكثر من مئتي طالب.", "The first lesson was in a big room with more than two hundred students."),
    ("تكلم المعلم عن الجسم والقلب، وكتبت كل كلمة.", "The teacher talked about the body and the heart, and I wrote every word."),
    ("في الغداء جلست مع رنا وصديقاتها في مطعم الجامعة.", "At lunch I sat with Rana and her friends in the university restaurant."),
    ("قلن لي أشياء كثيرة ومهمة عن الجامعة وعن الدروس.", "They told me many important things about the university and the lessons."),
    ("في المساء عدت إلى البيت، وكنت سعيدة جدا.", "In the evening I went home, and I was very happy."),
], q=[
    ("tf", "قامت الكاتبة من سريرها متأخرة.", "The writer got out of bed late.", False, ["قام", "سرير"], 1),
    ("mc", "إلى أين أخذت رنا الكاتبة؟", "Where did Rana take the writer?",
     ["إلى كلية الطب", "إلى المطعم", "إلى البيت", "إلى سوق المدينة"], ["أخذ", "كلية"], 3),
    ("mc", "في أي سنة تدرس رنا؟", "Which year is Rana in?",
     ["بعد السنة الثانية", "السنة الأولى", "السنة الثانية", "السنة الرابعة"], ["سنة", "ثالث"], 4),
    ("tf", "كان في الدرس الأول أكثر من مئتي طالب.", "There were more than two hundred students in the first lesson.",
     True, ["طالب", "مئة"], 6),
]))

P.append(dict(title="هدية لأمي", names=[], s=[
    ("في الأسبوع القادم عيد الأم، وأريد أن أشتري لها هدية.", "Next week is Mother's Day, and I want to buy her a present."),
    ("لكني لا أعرف ماذا أشتري.", "But I don't know what to buy."),
    ("أمي لا تحب الأشياء الغالية، وتقول دائما: لا أحتاج إلى شيء.", "My mother doesn't like expensive things, and she always says: I don't need anything."),
    ("سألت أختي، فقالت: اشتر لها وردة.", "I asked my sister, and she said: Buy her a flower."),
    ("وسألت أبي، فقال: أمك تحب الكتب.", "And I asked my father, and he said: Your mother loves books."),
    ("ذهبت إلى السوق ورأيت أشياء كثيرة جميلة.", "I went to the market and saw many beautiful things."),
    ("في دكان صغير وجدت ساعة قديمة مثل ساعة جدتي.", "In a small shop I found an old watch like my grandmother's watch."),
    ("تذكرت أن أمي كانت تحب ساعة جدتها كثيرا، لكنها فقدتها منذ سنوات.",
     "I remembered that my mother loved her grandmother's watch very much, but she lost it years ago."),
    ("كان سعرها مناسبا، فاشتريتها.", "Its price was reasonable, so I bought it."),
    ("يوم العيد أعطيت أمي الهدية.", "On the day I gave my mother the present."),
    ("عندما رأتها بكت قليلا، ثم قالت: هذه أحسن هدية في حياتي!",
     "When she saw it she cried a little, then said: This is the best present of my life!"),
    ("أنا أيضا كنت سعيدا جدا.", "I was very happy too."),
], q=[
    ("tf", "أم الكاتب تحب الأشياء الغالية.", "The writer's mother likes expensive things.", False, ["غال", "أحب"], 2),
    ("mc", "ماذا قال الأب؟", "What did the father say?",
     ["إن الأم تحب الكتب", "إن الأم تحب الزهور", "إن الأم لا تحتاج إلى شيء", "إن الأم تحب الساعات"], ["أب", "كتاب"], 4),
    ("mc", "ماذا اشترى الكاتب في النهاية؟", "What did the writer buy in the end?",
     ["ساعة", "كتابا", "وردة", "حقيبة"], ["ساعة", "قديم"], 6),
    ("tf", "بكت الأم عندما رأت الهدية.", "The mother cried when she saw the present.", True, ["هدية", "بكى"], 10),
]))

P.append(dict(title="الحقيبة", names=["نبيل"], s=[
    ("أمس أخذ نبيل الحافلة إلى وسط المدينة.", "Yesterday Nabil took the bus to the city centre."),
    ("كان معه حقيبة صغيرة فيها حاسوبه وأوراق مهمة من العمل.", "He had a small bag with him containing his computer and important papers from work."),
    ("كان في الحافلة ناس كثيرون، فوقف بجانب الباب.", "There were many people on the bus, so he stood by the door."),
    ("وضع الحقيبة على الأرض، وبدأ يقرأ رسالة على هاتفه.", "He put the bag on the floor, and started reading a message on his phone."),
    ("عندما وصل إلى المحطة نزل بسرعة، ونسي الحقيبة.", "When he reached the stop he got off quickly and forgot the bag."),
    ("بعد دقائق تذكرها، لكن الحافلة كانت قد ذهبت.", "A few minutes later he remembered it, but the bus had gone."),
    ("كان نبيل خائفا جدا، لأنه يحتاج إلى الأوراق في عمله غدا.", "Nabil was very frightened, because he needs the papers at work tomorrow."),
    ("اتصل بشركة الحافلات وقال لهم ما حدث.", "He called the bus company and told them what had happened."),
    ("قالت له الموظفة: انتظر، سأتصل بالرجل الذي يقود الحافلة.", "The employee said to him: Wait, I will call the man who drives the bus."),
    ("بعد نصف ساعة اتصلت به مرة أخرى وقالت: وجدنا حقيبتك!", "Half an hour later she called him again and said: We found your bag!"),
    ("ذهب نبيل إلى مكتب الشركة وأخذ الحقيبة، وكان كل شيء فيها.",
     "Nabil went to the company's office and took the bag, and everything was in it."),
    ("قال نبيل: شكرا جزيلا، أنتم أناس طيبون!", "Nabil said: Thank you very much, you are good people!"),
], q=[
    ("mc", "ماذا كان في الحقيبة؟", "What was in the bag?",
     ["حاسوب وأوراق", "ملابس وأحذية", "طعام وماء", "كتب وأقلام"], ["حقيبة", "حاسوب"], 1),
    ("tf", "جلس نبيل في الحافلة.", "Nabil sat down on the bus.", False, ["حافلة", "وقف"], 2),
    ("mc", "بمن اتصل نبيل؟", "Who did Nabil call?",
     ["بالشركة", "بالشرطة", "بمدير العمل", "بزوجته"], ["اتصل", "شركة"], 7),
    ("tf", "وجد نبيل كل شيء في الحقيبة.", "Nabil found everything in the bag.", True, ["حقيبة", "شيء"], 10),
]))

P.append(dict(title="الهاتف في حياتنا", names=[], s=[
    ("قبل عشرين سنة لم يكن عند أكثر الناس هاتف معهم دائما.", "Twenty years ago most people didn't always have a phone with them."),
    ("اليوم أصبح الهاتف جزءا من حياة كل إنسان تقريبا.", "Today the phone has become part of almost everyone's life."),
    ("نستخدمه لنتكلم مع الأصدقاء، ولنقرأ الأخبار، ولنشاهد الأفلام.", "We use it to talk with friends, read the news and watch films."),
    ("ونستخدمه أيضا لندفع في السوق، ولنعرف الطريق في مدينة لا نعرفها.",
     "And we also use it to pay at the market, and to find the way in a city we don't know."),
    ("هذا شيء جيد، لأن الحياة أصبحت سهلة.", "This is a good thing, because life has become easy."),
    ("لكن للهاتف مشاكل أيضا.", "But the phone has problems too."),
    ("كثير من الأطفال يجلسون أمام الهاتف ساعات طويلة كل يوم ولا يلعبون خارج البيت.",
     "Many children sit in front of the phone for long hours every day and don't play outside."),
    ("وبعض الناس لا يتكلمون مع عائلاتهم على الطعام، لأنهم ينظرون إلى هواتفهم.",
     "And some people don't talk to their families at meals, because they are looking at their phones."),
    ("يقول الأطباء إن استخدام الهاتف قبل النوم سيئ للصحة.", "Doctors say using the phone before sleeping is bad for health."),
    ("في بيتنا عندنا قاعدة: لا هواتف على طاولة الطعام.", "In our house we have a rule: no phones at the table."),
    ("أبي يقول إن الطعام وقت للكلام مع العائلة.", "My father says mealtime is a time for talking with the family."),
], q=[
    ("tf", "كان عند كل الناس هاتف قبل عشرين سنة.", "Everyone had a phone twenty years ago.", False, ["هاتف", "سنة"], 0),
    ("mc", "لماذا يقول الكاتب إن الهاتف شيء جيد؟", "Why does the writer say the phone is a good thing?",
     ["لأنه جعل الحياة سهلة", "لأنه رخيص", "لأن الأطفال يحبونه كثيرا", "لأنه جميل"], ["سهل", "حياة"], 4),
    ("mc", "ما القاعدة في بيت الكاتب؟", "What is the rule in the writer's house?",
     ["لا هواتف وقت الطعام", "لا أفلام بعد العشاء", "لا لعب بعد المدرسة", "لا نوم قبل الساعة 10"], ["قاعدة"], 9),
    ("tf", "يقول الأطباء إن الهاتف قبل النوم جيد.", "Doctors say the phone before sleep is good.", False, ["طبيب", "نوم"], 8),
]))

P.append(dict(title="حياة جدتي", names=[], s=[
    ("جدتي عمرها الآن خمسة وثمانون عاما.", "My grandmother is now eighty-five years old."),
    ("عندما أذهب إليها، تقول لي قصصا عن حياتها عندما كانت صغيرة.", "When I go to see her, she tells me stories about her life when she was young."),
    ("تقول إنها ولدت في قرية بعيدة، ولم يكن هناك ماء في البيوت.",
     "She says she was born in a distant village, and there was no water in the houses."),
    ("كانت تمشي كل صباح مع أمها إلى النهر لتأتي بالماء.", "Every morning she walked with her mother to the river to fetch water."),
    ("لم تكن في القرية مدرسة للبنات، ولذلك لم تتعلم القراءة والكتابة.",
     "There was no school for girls in the village, so she did not learn to read and write."),
    ("تزوجت جدي عندما كان عمرها سبعة عشر عاما.", "She married my grandfather when she was seventeen."),
    ("بعد الزواج ذهبا إلى المدينة، وعمل جدي في شركة كبيرة.", "After the wedding they went to the city, and my grandfather worked at a big company."),
    ("كانت الحياة صعبة، لكن جدتي تقول إن الناس كانوا سعداء أكثر من اليوم.",
     "Life was hard, but my grandmother says people were happier than today."),
    ("عندما كان عمرها ستين عاما، تعلمت القراءة في برنامج لتعليم الكبار.",
     "When she was sixty, she learned to read in a programme for teaching adults."),
    ("الآن تقرأ الأخبار كل صباح، وتقول إن هذا أحسن شيء في حياتها.",
     "Now she reads the news every morning, and says this is the best thing in her life."),
], q=[
    ("mc", "أين ولدت الجدة؟", "Where was the grandmother born?",
     ["في قرية", "في المدينة", "في بيت جدها", "في بلد آخر"], ["ولد", "قرية"], 2),
    ("tf", "ذهبت الجدة إلى المدرسة عندما كانت صغيرة.", "The grandmother went to school when she was young.", False, ["مدرسة"], 4),
    ("mc", "كم كان عمر الجدة عندما تزوجت؟", "How old was the grandmother when she married?",
     ["سبعة عشر عاما", "ستين عاما", "خمسة وعشرين عاما", "خمسة عشر عاما"], ["تزوج", "عمر"], 5),
    ("tf", "تعلمت الجدة القراءة عندما كانت كبيرة.", "The grandmother learned to read when she was older.", True, ["تعلم", "قراءة"], 8),
]))
