# B1 passages (p0041-p0060); format as a1.py
P = []

P.append(dict(title="عطلة على الشاطئ", names=["لبنى", "سامي"], s=[
    ("في الصيف الماضي قضت لبنى وزوجها سامي عطلة قصيرة على شاطئ البحر.",
     "Last summer Lubna and her husband Sami spent a short holiday on the seashore."),
    ("حجزا غرفة في فندق صغير قبل شهرين، لأن الفنادق تكون مليئة في هذا الموسم.",
     "They booked a room in a small hotel two months ahead, because hotels are full in this season."),
    ("وصلا في المساء بعد رحلة طويلة بالقطار.", "They arrived in the evening after a long train journey."),
    ("كانت الغرفة نظيفة، ومن النافذة كان البحر واضحا.", "The room was clean, and the sea was clear from the window."),
    ("في الأيام الأولى كان الطقس رائعا، فقضيا ساعات طويلة على الشاطئ.",
     "In the first days the weather was wonderful, so they spent long hours on the beach."),
    ("سامي يحب السباحة كثيرا، أما لبنى فتفضل أن تجلس تحت الشمس وتقرأ رواية.",
     "Sami loves swimming, while Lubna prefers to sit in the sun and read a novel."),
    ("في المساء كانا يمشيان في الشوارع القديمة ويأكلان السمك في المطاعم الصغيرة.",
     "In the evening they walked in the old streets and ate fish in the small restaurants."),
    ("الطعام كان لذيذا، والأسعار كانت مناسبة.", "The food was delicious, and the prices were reasonable."),
    ("لكن في اليوم الرابع جاءت عاصفة قوية، واستمر المطر يومين كاملين.",
     "But on the fourth day a strong storm came, and the rain continued for two whole days."),
    ("لم يستطيعا أن يخرجا من الفندق، فلعبا الورق وشاهدا الأفلام.",
     "They could not leave the hotel, so they played cards and watched films."),
    ("قالت لبنى إن هذين اليومين كانا أجمل وقت في العطلة، لأنهما تكلما كثيرا.",
     "Lubna said those two days were the best time of the holiday, because they talked a lot."),
    ("في اليوم الأخير عاد الطقس جميلا، فذهبا إلى الشاطئ مرة أخرى.",
     "On the last day the weather was fine again, so they went back to the beach."),
    ("عندما عادا إلى المدينة، قررا أن يعودا إلى المكان نفسه في السنة القادمة.",
     "When they returned to the city, they decided to go back to the same place next year."),
], q=[
    ("mc", "لماذا حجز الزوجان الغرفة قبل شهرين؟", "Why did the couple book the room two months ahead?",
     ["لأن الفنادق لا يبقى فيها مكان في الصيف", "لأن السعر كان أقل في ذلك الوقت من السنة", "لأن الفندق كان جديدا", "لأن سامي أراد مفاجأة"], ["حجز", "فندق"], 1),
    ("tf", "لبنى تحب السباحة أكثر من القراءة.", "Lubna likes swimming more than reading.", False, ["سباحة", "فضل"], 5),
    ("tf", "بقي الزوجان في الفندق بسبب الطقس.", "The couple stayed in the hotel because of the weather.", True, ["فندق", "خرج"], 9),
    ("mc", "ماذا قالت لبنى عن يومي المطر؟", "What did Lubna say about the two rainy days?",
     ["كانا أحسن وقت في العطلة", "كانا صعبين جدا", "كانا سبب عودتهما مبكرا", "كانا أسوأ أيام حياتها"], ["قال", "يوم"], 10),
    ("mc", "ماذا قرر الزوجان في النهاية؟", "What did the couple decide in the end?",
     ["أن يزورا المكان مرة ثانية", "أن يشتريا بيتا هناك", "ألا يسافرا في الصيف", "أن يذهبا إلى الجبل"], ["قرر"], 12),
]))

P.append(dict(title="العمل من البيت", names=[], s=[
    ("في السنوات الأخيرة أصبح كثير من الناس يعملون من البيت.", "In recent years many people have started working from home."),
    ("هذا النوع من العمل له فوائد واضحة.", "This kind of work has clear benefits."),
    ("أولا، لا يحتاج الموظف إلى أن يقضي ساعة أو أكثر كل يوم في الطريق.",
     "First, the employee does not need to spend an hour or more every day on the road."),
    ("وهذا يعني وقتا أطول مع الأسرة، ومالا أقل للوقود والحافلات.",
     "This means more time with the family, and less money on fuel and buses."),
    ("ثانيا، يستطيع الإنسان أن ينظم وقته كما يريد.", "Second, a person can organise their time as they like."),
    ("لكن العمل من البيت ليس سهلا دائما.", "But working from home is not always easy."),
    ("بعض الناس يشعرون بالوحدة، لأنهم لا يرون زملاءهم.", "Some people feel lonely, because they don't see their colleagues."),
    ("وبعضهم يجدون صعوبة في التركيز، خاصة إذا كان في البيت أطفال صغار.",
     "And some find it hard to concentrate, especially if there are small children at home."),
    ("هناك أيضا مشكلة أخرى: الحدود بين العمل والحياة الخاصة تختفي.",
     "There is also another problem: the line between work and private life disappears."),
    ("كثير من الموظفين يقرؤون رسائل العمل في الليل وفي العطلة.", "Many employees read work messages at night and on holidays."),
    ("لذلك يقول الخبراء إن من الأفضل أن يكون للعمل مكان خاص في البيت، وساعات محددة.",
     "So experts say it is better to have a special place for work at home, and fixed hours."),
    ("ومن المفيد أيضا أن يخرج الإنسان من البيت مرة في اليوم على الأقل.", "It is also useful to leave the house at least once a day."),
    ("اليوم تسمح شركات كثيرة لموظفيها بأن يعملوا يومين في البيت وثلاثة أيام في المكتب.",
     "Today many companies let their employees work two days at home and three days at the office."),
], q=[
    ("mc", "ما الفائدة الأولى للعمل من البيت كما يقول النص؟", "What is the first benefit of working from home, according to the text?",
     ["لا يضيع الموظف وقتا في الطريق", "يربح الموظف مالا أكثر في كل شهر", "يرى الموظف زملاءه أكثر", "يعمل الموظف ساعات أقل"], ["احتاج", "طريق"], 2),
    ("tf", "كل الناس يجدون العمل من البيت سهلا.", "Everyone finds working from home easy.", False, ["عمل", "سهل"], 5),
    ("mc", "لماذا يشعر بعض الناس بالوحدة؟", "Why do some people feel lonely?",
     ["لا يرون من يعملون معهم", "يسكنون بعيدا عن أسرهم", "لا يحبون عملهم", "ليس عندهم إنترنت"], ["زميل"], 6),
    ("tf", "يرى الخبراء أن العمل يحتاج إلى وقت محدد.", "Experts think work needs set times.", True, ["خبير", "محدد"], 10),
]))

P.append(dict(title="مهرجان الكتاب", names=["المغرب"], s=[
    ("بدأ أمس مهرجان الكتاب السنوي في ساحة المدينة الكبيرة.", "The annual book festival began yesterday in the city's main square."),
    ("يشارك في المهرجان هذا العام أكثر من مئتي دار نشر من عشرين بلدا.",
     "More than two hundred publishers from twenty countries are taking part in the festival this year."),
    ("وسيستمر عشرة أيام، من الساعة العاشرة صباحا حتى العاشرة مساء.",
     "It will last ten days, from ten in the morning until ten in the evening."),
    ("الدخول مجاني للجميع، والأطفال لهم قسم خاص فيه كتب وألعاب ومسرحيات قصيرة.",
     "Entry is free for everyone, and children have a special section with books, games and short plays."),
    ("في اليوم الأول جاء آلاف الناس، رغم الحر الشديد.", "On the first day thousands of people came, despite the intense heat."),
    ("قال رجل إنه يأتي إلى المهرجان كل سنة منذ عشر سنوات.", "One man said he has come to the festival every year for ten years."),
    ("وأضاف أن الكتب هنا ليست غالية مثل المكتبات، وأن الاختيار أكبر.", "He added that books here are not as expensive as in bookshops, and the choice is bigger."),
    ("هذا العام ضيف الشرف هو المغرب.", "This year the guest of honour is Morocco."),
    ("سيقدم كتاب وشعراء من هناك أعمالهم الجديدة، ويتكلمون عن الأدب والثقافة في بلدهم.",
     "Writers and poets from there will present their new works and talk about literature and culture in their country."),
    ("ويقدم المهرجان أيضا برنامجا لمساعدة الشباب على القراءة.", "The festival also offers a programme to help young people read."),
    ("تقول المسؤولة عن البرنامج إن الشباب اليوم يقرؤون على الهاتف أكثر من الكتب.",
     "The woman in charge of the programme says young people today read on their phones more than in books."),
    ("لكنها ترى أن هذا ليس سيئا، لأن الشيء المهم أن يقرؤوا.", "But she thinks this is not bad, because the important thing is that they read."),
    ("في نهاية المهرجان ستعطى هدية لأفضل رواية عربية لهذا العام.", "At the end of the festival a gift will be given for the best Arabic novel of the year."),
], q=[
    ("mc", "كم يوما يستمر المهرجان؟", "How many days does the festival last?",
     ["عشرة أيام", "أسبوعا واحدا", "عشرين يوما", "شهرا"], ["استمر", "يوم"], 2),
    ("tf", "يجب أن يدفع الناس للدخول.", "People must pay to get in.", False, ["دخول", "مجاني"], 3),
    ("mc", "لماذا يحب الرجل المهرجان؟", "Why does the man like the festival?",
     ["لأن الكتب فيه أقل سعرا", "لأنه يعمل هناك", "لأنه يلتقي بأصدقائه", "لأن الدخول قريب من بيته"], ["كتاب", "غال"], 6),
    ("tf", "المسؤولة عن البرنامج ترى أن القراءة على الهاتف شيء سيئ جدا.", "The programme manager thinks reading on the phone is very bad.",
     False, ["رأى", "سيئ"], 11),
]))

P.append(dict(title="مشكلة الماء", names=[], s=[
    ("يعيش ملايين الناس في العالم العربي في مناطق فيها ماء قليل.", "Millions of people in the Arab world live in areas with little water."),
    ("المطر في هذه المناطق قليل، والأنهار قليلة أيضا.", "Rain in these regions is scarce, and so are rivers."),
    ("ومع ارتفاع عدد السكان، يزداد الطلب على الماء كل سنة.", "And as the population rises, demand for water increases every year."),
    ("يستخدم الناس الماء في البيوت، لكن أكثر الماء يستخدم لإنتاج الطعام.",
     "People use water in their homes, but most of the water is used to produce food."),
    ("لذلك تبحث الحكومات عن حلول مختلفة.", "So governments are looking for different solutions."),
    ("بعض الدول تأخذ الماء من البحر وتجعله صالحا للشرب.", "Some countries take water from the sea and make it fit to drink."),
    ("هذه الطريقة مفيدة، لكنها غالية جدا، وتحتاج إلى طاقة كثيرة.",
     "This method is useful, but very expensive, and needs a lot of energy."),
    ("وهناك دول أخرى تستعمل الماء مرة ثانية بعد تنظيفه.", "Other countries use water a second time after cleaning it."),
    ("ويقول الخبراء إن كل واحد منا يستطيع أن يساعد.", "Experts say each of us can help."),
    ("على سبيل المثال، نستطيع أن نغلق الماء عندما لا نحتاج إليه، وأن نصلح أي مشكلة في البيت بسرعة.",
     "For example, we can turn off the water when we don't need it, and fix any problem at home quickly."),
    ("قد تبدو هذه أشياء صغيرة، لكنها إذا جمعناها تصبح كبيرة جدا.",
     "These may seem small things, but when we add them up they become very big."),
    ("الماء ليس شيئا لا ينتهي، ويجب أن نستعمله بعقل من أجل الأجيال القادمة.",
     "Water is not something endless, and we must use it wisely for the sake of future generations."),
], q=[
    ("mc", "أين يذهب أكثر الماء؟", "Where does most of the water go?",
     ["لإنتاج الطعام", "للبيوت", "للمصانع", "للبحر"], ["ماء", "إنتاج"], 3),
    ("tf", "أخذ الماء من البحر طريقة رخيصة.", "Taking water from the sea is a cheap method.", False, ["طريقة", "غال"], 6),
    ("mc", "ماذا يفعل بعض الدول بالماء بعد تنظيفه؟", "What do some countries do with water after cleaning it?",
     ["تستعمله مرة ثانية", "ترسله إلى البحر", "تبيعه لدول أخرى بسعر عال", "تتركه في الأرض"], ["استعمل", "تنظيف"], 7),
    ("tf", "يرى الخبراء أن كل إنسان يستطيع أن يساعد.", "Experts think every person can help.", True, ["خبير", "ساعد"], 8),
]))

P.append(dict(title="رسالة شكوى", names=["فراس", "دبي", "القاهرة"], s=[
    ("إلى شركة الطيران،", "To the airline,"),
    ("أكتب إليكم لأخبركم عن مشكلة حدثت في رحلتي الأخيرة.", "I am writing to tell you about a problem that happened on my last flight."),
    ("يوم الخميس الماضي سافرت من دبي إلى القاهرة.", "Last Thursday I flew from Dubai to Cairo."),
    ("كان موعد الطائرة في الساعة الثامنة صباحا، لكنها تأخرت خمس ساعات.",
     "The plane was due at eight in the morning, but it was five hours late."),
    ("لم يقل لنا أحد سبب التأخر، ولم يعطنا أحد طعاما أو ماء.", "Nobody told us the reason for the delay, and nobody gave us food or water."),
    ("وعندما وصلت إلى القاهرة، اكتشفت أن حقيبتي لم تصل.", "And when I arrived in Cairo, I discovered that my bag had not arrived."),
    ("انتظرت في المطار ساعتين، ثم قال لي موظف إن الحقيبة ستصل غدا.",
     "I waited at the airport for two hours, then an employee told me the bag would arrive the next day."),
    ("لكنها لم تصل إلا بعد أربعة أيام.", "But it only arrived after four days."),
    ("كان في الحقيبة ملابسي وأوراق مهمة لاجتماع عمل، فاضطررت أن أشتري ملابس جديدة.",
     "My clothes and important papers for a work meeting were in the bag, so I had to buy new clothes."),
    ("أنا أسافر معكم منذ سنوات طويلة، ولم تحدث لي مشكلة مثل هذه من قبل.",
     "I have flown with you for many years, and I have never had a problem like this before."),
    ("لذلك أطلب منكم أن تدفعوا لي ثمن الملابس التي اشتريتها، وأرسل لكم صورة الأوراق.",
     "So I ask you to pay me for the clothes I bought, and I am sending you a picture of the papers."),
    ("أرجو أن أسمع منكم قريبا.", "I hope to hear from you soon."),
    ("مع الاحترام، فراس.", "Respectfully, Firas."),
], q=[
    ("mc", "كم ساعة تأخرت الطائرة؟", "How many hours was the plane late?",
     ["خمس ساعات", "ساعتين", "أربع ساعات", "ثماني ساعات"], ["تأخر"], 3),
    ("tf", "أعطت الشركة الناس طعاما أثناء الانتظار.", "The company gave people food during the wait.", False, ["طعام"], 4),
    ("mc", "متى وصلت الحقيبة؟", "When did the bag arrive?",
     ["بعد أربعة أيام", "في اليوم التالي", "بعد ساعتين", "بعد أسبوع"], ["وصل"], 7),
    ("tf", "هذه أول مرة تحدث لفراس مشكلة مع هذه الشركة.", "This is the first time Firas has had a problem with this airline.",
     True, ["مشكلة", "حدث"], 9),
    ("mc", "ماذا يطلب فراس من الشركة؟", "What does Firas ask the company for?",
     ["أن تدفع ثمن ملابسه", "أن تعطيه تذكرة مجانية", "أن تعتذر فقط", "أن ترسل له حقيبة جديدة"], ["طلب", "ثمن"], 10),
]))

P.append(dict(title="قصة نجاح", names=["ليلى"], s=[
    ("ولدت ليلى في قرية صغيرة، في أسرة فقيرة فيها سبعة أطفال.", "Laila was born in a small village, into a poor family with seven children."),
    ("لم يكن أبوها يستطيع أن يدفع ثمن الكتب، فكانت تأخذ الكتب من جيرانها ثم تعيدها.",
     "Her father could not afford books, so she took books from her neighbours and then gave them back."),
    ("كانت تحب العلوم منذ كانت طفلة، وتحلم بأن تصبح طبيبة.", "She loved science from a young age, and dreamed of becoming a doctor."),
    ("بعد المدرسة كانت تساعد أمها في البيت، ثم تدرس حتى وقت متأخر في الليل.",
     "After school she helped her mother at home, then studied until late at night."),
    ("في نهاية المدرسة حصلت على أعلى درجة في المنطقة كلها.", "At the end of school she got the highest mark in the whole region."),
    ("بفضل ذلك حصلت على مكان في جامعة في العاصمة بدون أن تدفع شيئا.", "Thanks to that she got a place at a university in the capital without paying anything."),
    ("لكن الحياة في المدينة كانت صعبة عليها في البداية.", "But life in the city was hard for her at first."),
    ("لم تكن تعرف أحدا، وكانت تعمل في مطعم في المساء لتدفع ثمن السكن.",
     "She didn't know anyone, and she worked in a restaurant in the evenings to pay for her housing."),
    ("رغم ذلك أكملت دراستها بنجاح، وأصبحت طبيبة أطفال.", "Despite that she completed her studies successfully, and became a paediatrician."),
    ("اليوم تعمل ليلى في مستشفى كبير، لكنها لم تنس قريتها.", "Today Laila works in a big hospital, but she has not forgotten her village."),
    ("مرة في الشهر تعود إلى هناك وترى الأطفال المرضى بدون مقابل.", "Once a month she goes back there and sees sick children free of charge."),
    ("وقد فتحت أيضا مكتبة صغيرة للأطفال في بيت أسرتها القديم.", "She has also opened a small children's library in her family's old house."),
    ("تقول ليلى: لم يكن عندي كتب، ولا أريد أن يعيش طفل آخر هذه التجربة.",
     "Laila says: I had no books, and I don't want another child to go through that."),
], q=[
    ("mc", "كيف كانت ليلى تحصل على الكتب؟", "How did Laila get books?",
     ["كانت تأخذها من الجيران", "كان أبوها يشتريها", "كانت تشتريها من المدرسة", "كانت تجدها على الإنترنت"], ["كتاب", "جار"], 1),
    ("tf", "كانت ليلى تعمل في مطعم أثناء دراستها.", "Laila worked in a restaurant while she was studying.", True, ["مطعم", "عمل"], 7),
    ("mc", "ماذا تفعل ليلى في قريتها مرة في الشهر؟", "What does Laila do in her village once a month?",
     ["تساعد الأطفال ولا تأخذ مالا", "تعلم في المدرسة ثم تعود إلى البيت", "تزور أمها فقط", "تبيع الكتب"], ["شهر", "طفل"], 10),
    ("tf", "نسيت ليلى قريتها بعد أن أصبحت طبيبة.", "Laila forgot her village after she became a doctor.", False, ["نسي", "قرية"], 9),
]))

P.append(dict(title="المدينة القديمة", names=[], s=[
    ("تقع المدينة القديمة في قلب العاصمة، وعمرها أكثر من ألف سنة.",
     "The old city lies in the heart of the capital, and it is more than a thousand years old."),
    ("حولها جدار عال فيه سبع بوابات كبيرة.", "Around it is a high wall with seven big gates."),
    ("في داخلها شوارع ضيقة، وبيوت قديمة من الحجر، وأسواق تقليدية.",
     "Inside there are narrow streets, old stone houses and traditional markets."),
    ("في الماضي كان يسكن فيها التجار والفنانون والعلماء.", "In the past merchants, artists and scholars lived there."),
    ("ما زالت بعض العائلات تعيش هناك حتى اليوم، في البيوت نفسها التي عاش فيها أجدادها.",
     "Some families still live there today, in the same houses their ancestors lived in."),
    ("في القرن الماضي تركها كثير من السكان، وانتقلوا إلى الأحياء الجديدة.",
     "In the last century many residents left it and moved to the new neighbourhoods."),
    ("فأصبحت بعض البيوت فارغة، وبدأت تسقط.", "So some houses became empty and started to fall down."),
    ("لكن قبل عشرين سنة بدأت الحكومة برنامجا لإصلاح المدينة القديمة.",
     "But twenty years ago the government started a programme to restore the old city."),
    ("تم إصلاح مئات البيوت، وتحول بعضها إلى فنادق صغيرة ومطاعم.",
     "Hundreds of houses were restored, and some were turned into small hotels and restaurants."),
    ("اليوم يزور المدينة القديمة آلاف الناس من كل العالم كل أسبوع.", "Today thousands of people from all over the world visit the old city every week."),
    ("هذا شيء جيد للاقتصاد، لكن بعض السكان غير سعداء.", "This is good for the economy, but some residents are not happy."),
    ("هم يقولون إن الأسعار ارتفعت كثيرا، وإن المدينة فقدت هدوءها.",
     "They say prices have risen a lot, and the city has lost its calm."),
    ("ويطلبون من الحكومة أن تهتم بحياة الناس، لا بالحجر فقط.",
     "And they ask the government to care about people's lives, not just the stones."),
], q=[
    ("mc", "كم بوابة في جدار المدينة القديمة؟", "How many gates are in the old city's wall?",
     ["سبع بوابات", "خمس بوابات", "عشر بوابات", "بوابتان"], ["بوابة"], 1),
    ("tf", "كل سكان المدينة القديمة تركوها.", "All the residents of the old city left it.", False, ["عائلة", "عاش"], 4),
    ("mc", "ماذا بدأت الحكومة قبل عشرين سنة؟", "What did the government start twenty years ago?",
     ["برنامجا لإصلاح البيوت", "بناء مدينة جديدة", "بناء جدار جديد", "برنامجا لتعليم الأطفال"], ["حكومة", "برنامج"], 7),
    ("tf", "بعض السكان يقولون إن الأسعار أصبحت عالية.", "Some residents say prices have become high.", True, ["سعر", "ارتفع"], 11),
]))

P.append(dict(title="السكر في حياتنا", names=[], s=[
    ("تغيرت عادات الطعام في بلادنا كثيرا في الثلاثين سنة الأخيرة.", "Eating habits in our countries have changed a lot in the last thirty years."),
    ("في الماضي كانت الأسرة تأكل معا في البيت، وكان الطعام بسيطا: خبز ولحم وفاكهة.",
     "In the past the family ate together at home, and the food was simple: bread, meat and fruit."),
    ("أما اليوم فكثير من الناس يأكلون في الشارع أو يطلبون الطعام بالهاتف.",
     "Today, though, many people eat in the street or order food by phone."),
    ("هذا الطعام سريع ولذيذ، لكن فيه سكر كثير.", "This food is quick and tasty, but it has a lot of sugar."),
    ("وكثير من الأطفال يشربون المشروبات الحلوة كل يوم بدلا من الماء والحليب.",
     "And many children drink sweet drinks every day instead of water and milk."),
    ("ونتيجة لذلك ارتفع عدد الناس الذين يعانون من زيادة الوزن، حتى بين الأطفال.",
     "As a result the number of people suffering from being overweight has risen, even among children."),
    ("ويقول الأطباء إن هذا يسبب أمراضا خطيرة في القلب.", "Doctors say this causes serious heart disease."),
    ("لكن الحل ليس صعبا.", "But the solution is not difficult."),
    ("يقول الأطباء إن علينا أن نأكل الفاكهة كل يوم، وأن نشرب الماء بدلا من المشروبات الحلوة.",
     "Doctors say we should eat fruit every day, and drink water instead of sweet drinks."),
    ("ومن الأفضل أيضا أن نعمل الطعام في البيت عندما نستطيع، لأننا نعرف ما نضعه فيه.",
     "It is also better to make food at home when we can, because we know what we put in it."),
    ("بعض المدارس بدأت تعلم الأطفال كيف يختارون وجبة صحية.", "Some schools have started teaching children how to choose a healthy meal."),
    ("وفي بعض المدارس لا يبيعون الحلوى أبدا.", "And some schools never sell sweets."),
    ("الطعام الجيد لا يجب أن يكون غاليا؛ الشيء المهم أن نختار بعقل.", "Good food doesn't have to be expensive; the important thing is to choose wisely."),
], q=[
    ("mc", "كيف كان الطعام في الماضي حسب النص؟", "What was food like in the past, according to the text?",
     ["لم يكن معقدا", "غاليا جدا", "سريعا", "حلوا"], ["طعام", "بسيط"], 1),
    ("tf", "الطعام في الشارع فيه سكر قليل.", "Street food has little sugar.", False, ["سكر"], 3),
    ("mc", "ماذا يقول الأطباء إن علينا أن نشرب؟", "What do doctors say we should drink?",
     ["ماء", "حليبا", "قهوة", "شايا"], ["شرب", "بدلا من"], 8),
    ("tf", "بعض المدارس تعلم الأطفال اختيار طعام صحي.", "Some schools teach children to choose healthy food.", True, ["مدرسة", "وجبة"], 10),
]))

P.append(dict(title="جاري الجديد", names=["سالم"], s=[
    ("قبل ثلاثة أشهر انتقل إلى الشقة التي بجانبنا رجل عجوز يعيش وحده.",
     "Three months ago an old man who lives alone moved into the flat next to ours."),
    ("في البداية لم يكن يتكلم مع أحد، وكان يخرج فقط ليشتري الخبز.",
     "At first he didn't talk to anyone, and only went out to buy bread."),
    ("كان الجيران يقولون إنه رجل غريب، وكان الأطفال يخافون منه.", "The neighbours said he was a strange man, and the children were afraid of him."),
    ("في يوم من الأيام رأيته يحمل حقائب ثقيلة أمام الباب، فساعدته.",
     "One day I saw him carrying heavy bags at the door, so I helped him."),
    ("شكرني كثيرا، ودعاني إلى القهوة.", "He thanked me a lot and invited me for coffee."),
    ("في شقته رأيت مئات الكتب القديمة وصورا من بلاد كثيرة.", "In his flat I saw hundreds of old books and pictures from many countries."),
    ("عرفت أن اسمه سالم، وأنه كان يعمل على سفينة أربعين سنة.",
     "I found out that his name is Salim, and that he worked on a ship for forty years."),
    ("زار أكثر من خمسين بلدا، ويتكلم أربع لغات.", "He visited more than fifty countries, and speaks four languages."),
    ("قال لي إن زوجته ماتت قبل سنة، وإن أولاده يعيشون في الخارج.",
     "He told me his wife died a year ago, and that his children live abroad."),
    ("منذ ذلك اليوم أزوره مرة في الأسبوع.", "Since that day I visit him once a week."),
    ("يقول لي قصصا عن البحر والموانئ والناس الذين التقى بهم.", "He tells me stories about the sea, the ports and the people he met."),
    ("الآن يعرفه كل الجيران، والأطفال يأتون إليه ليسمعوا قصصه.",
     "Now all the neighbours know him, and the children come to him to hear his stories."),
    ("تعلمت منه أن الإنسان الغريب قد يكون فقط إنسانا وحيدا.", "I learned from him that a strange person may simply be a lonely person."),
], q=[
    ("tf", "كان الجار الجديد يتكلم مع كل الجيران من اليوم الأول.", "The new neighbour talked with all the neighbours from the first day.",
     False, ["تكلم"], 1),
    ("mc", "كيف تعرف الكاتب على جاره؟", "How did the writer get to know his neighbour?",
     ["ساعده في حمل حقائبه", "التقى به في المسجد بعد الصلاة", "ذهب إلى شقته", "رآه في السوق"], ["ساعد"], 3),
    ("mc", "ماذا كان عمل سالم؟", "What was Salim's job?",
     ["كان يعمل في البحر", "كان معلما", "كان طبيبا", "كان تاجرا"], ["عمل", "سفينة"], 6),
    ("tf", "أولاد سالم يعيشون في بلد آخر.", "Salim's children live in another country.", True, ["ولد", "عاش"], 8),
    ("mc", "ماذا تعلم الكاتب من جاره؟", "What did the writer learn from his neighbour?",
     ["أن الغريب قد يكون وحيدا فقط", "أن السفر خطير على الناس الكبار", "أن البحر جميل", "أن الكتب القديمة غالية"], ["تعلم"], 12),
]))

P.append(dict(title="التعلم على الإنترنت", names=[], s=[
    ("لم يعد التعليم اليوم مرتبطا بالمدرسة أو الجامعة فقط.", "Education today is no longer tied only to school or university."),
    ("على الإنترنت آلاف الدروس المجانية في كل المجالات، من اللغات إلى الطب والموسيقى.",
     "On the internet there are thousands of free lessons in every field, from languages to medicine and music."),
    ("يستطيع أي شخص عنده حاسوب أو هاتف أن يتعلم ما يريد، في الوقت الذي يريده.",
     "Anyone with a computer or phone can learn what they want, at the time they want."),
    ("هذا مفيد خاصة للذين يعملون، أو يسكنون بعيدا عن المدن الكبيرة.",
     "This is useful especially for those who work, or live far from big cities."),
    ("لكن التعلم على الإنترنت يحتاج إلى وقت وجهد كبير.", "But learning online needs time and a lot of effort."),
    ("كثير من الناس يبدؤون دورة وهم سعداء جدا، ثم يتركونها بعد أسابيع قليلة.",
     "Many people start a course very happy, then drop it after a few weeks."),
    ("السبب أن لا أحد يراقبهم، ولا أحد يسألهم عن واجباتهم.", "The reason is that nobody watches them, and nobody asks them about their homework."),
    ("لذلك يقول الخبراء إن بعض الأشياء البسيطة تساعد كثيرا.", "So experts say a few simple things help a lot."),
    ("أولا، اختر ساعة محددة كل يوم للدراسة، مثل موعد في المدرسة.", "First, choose a fixed hour every day for study, like an appointment at school."),
    ("ثانيا، ادرس مع صديق، أو انضم إلى مجموعة من الطلاب على الإنترنت.",
     "Second, study with a friend, or join a group of students online."),
    ("ثالثا، لا تحاول أن تتعلم كل شيء في وقت واحد، بل خطوة بعد خطوة.", "Third, don't try to learn everything at once, but step by step."),
    ("وأخيرا، تذكر لماذا بدأت، واكتب هدفك في مكان تراه كل يوم.", "Finally, remember why you started, and write your goal somewhere you see it every day."),
], q=[
    ("tf", "كل الدروس على الإنترنت غالية.", "All lessons online are expensive.", False, ["درس", "مجاني"], 1),
    ("mc", "لماذا يترك كثير من الناس الدورة؟", "Why do many people drop the course?",
     ["لأن لا أحد يتابعهم", "لأن الدروس صعبة جدا", "لأن الإنترنت بطيء", "لأنهم يجدون عملا"], ["راقب"], 6),
    ("mc", "ما أول شيء يقوله الخبراء؟", "What is the first thing the experts say?",
     ["أن تدرس في ساعة محددة كل يوم", "أن تشتري حاسوبا جديدا وكتبا كثيرة", "أن تدرس في الليل فقط", "أن تترك العمل"], ["اختار", "ساعة"], 8),
    ("tf", "يقول النص إن علينا أن نتعلم شيئا بعد شيء.", "The text says we should learn one thing after another.", True, ["تعلم", "خطوة"], 10),
]))

P.append(dict(title="العيد في بيتنا", names=[], s=[
    ("العيد عندنا ليس يوما واحدا، بل أيام سعيدة من الزيارات.", "For us the holiday is not one day, but happy days of visits."),
    ("قبل العيد بأسبوع تبدأ أمي تنظيف البيت كله، ونساعدها كلنا.", "A week before the holiday my mother starts cleaning the whole house, and we all help her."),
    ("ثم تذهب مع أختي إلى السوق لتشتري ملابس جديدة للأطفال.", "Then she goes with my sister to the market to buy new clothes for the children."),
    ("في الليلة الأخيرة قبل العيد تعمل أمي وجدتي الحلوى في المطبخ حتى وقت متأخر.",
     "On the last night before the holiday my mother and grandmother make sweets in the kitchen until late."),
    ("رائحة الحلوى في كل البيت، ولا يستطيع أحد أن ينام.", "The smell of the sweets is all over the house, and nobody can sleep."),
    ("في صباح العيد نلبس الملابس الجديدة ونذهب إلى الصلاة مع أبي.", "On the morning of the holiday we put on the new clothes and go to prayer with my father."),
    ("بعد ذلك نزور جدي وجدتي، ثم عائلة أبي وعائلة أمي.", "After that we visit my grandparents, then my father's family and my mother's family."),
    ("الكبار يعطون الأطفال مالا، والأطفال يشترون به ألعابا وحلوى.", "The grown-ups give the children money, and the children buy toys and sweets with it."),
    ("في اليوم الثاني يأتي الناس إلى بيتنا، ونقدم لهم القهوة والحلوى.", "On the second day people come to our house, and we offer them coffee and sweets."),
    ("في الماضي كانت العائلة كلها تسكن في مدينة واحدة.", "In the past the whole family lived in one city."),
    ("أما الآن فبعض أفراد عائلتي يعيشون في الخارج، ولا يأتون إلا مرة كل سنتين.",
     "Now, though, some members of my family live abroad, and only come once every two years."),
    ("لذلك نتكلم معهم على الهاتف، ونرى وجوههم على الشاشة.", "So we talk to them on the phone, and see their faces on the screen."),
    ("ليس هذا مثل أن نجلس معا، لكنه أفضل من لا شيء.", "It's not like sitting together, but it's better than nothing."),
], q=[
    ("mc", "ماذا تفعل الأم قبل العيد بأسبوع؟", "What does the mother do a week before the holiday?",
     ["تبدأ تنظيف البيت", "تسافر إلى الخارج", "تزور جدتها", "تعمل الحلوى"], ["تنظيف", "أسبوع"], 1),
    ("tf", "ينام الجميع في وقت مبكر ليلة العيد.", "Everyone goes to sleep early on the eve of the holiday.", False, ["نام"], 4),
    ("mc", "ماذا يفعل الأطفال بالمال؟", "What do the children do with the money?",
     ["يشترون أشياء يلعبون بها", "يعطونه لأمهم", "يضعونه في البنك", "يعطونه للفقراء"], ["مال", "اشترى"], 7),
    ("tf", "كل أفراد العائلة يعيشون في المدينة نفسها.", "All the family members live in the same city.", False, ["فرد", "عاش"], 10),
    ("tf", "ترى العائلة من يعيش في الخارج على الشاشة.", "The family sees those living abroad on the screen.", True, ["شاشة"], 11),
]))

P.append(dict(title="مقابلة مع لاعب", names=["ياسر"], s=[
    ("ياسر لاعب كرة قدم شاب، انضم هذا الموسم إلى فريق كبير في العاصمة.",
     "Yasser is a young footballer who joined a big team in the capital this season."),
    ("سألناه عن حياته وعن أحلامه.", "We asked him about his life and his dreams."),
    ("متى بدأت تلعب كرة القدم؟", "When did you start playing football?"),
    ("بدأت في الشارع أمام بيتنا، عندما كان عمري ست سنوات.", "I started in the street in front of our house, when I was six years old."),
    ("كنا نلعب بكرة قديمة، وكانت حقائبنا أهدافنا.", "We played with an old ball, and our bags were our goals."),
    ("من ساعدك أكثر في طريقك؟", "Who helped you most along the way?"),
    ("أبي، بدون شك.", "My father, without a doubt."),
    ("كان يعمل ساعات طويلة، لكنه كان يأخذني إلى التدريب كل يوم.", "He worked long hours, but he took me to training every day."),
    ("وكان مدربي الأول يقول لي دائما إن الموهبة وحدها لا تكفي، وإن العمل أهم.",
     "And my first coach always told me that talent alone is not enough, and that work matters more."),
    ("ما الشيء الصعب جدا في حياة اللاعب؟", "What is the really hard thing in a player's life?"),
    ("الإصابات، بدون شك.", "Injuries, without a doubt."),
    ("قبل سنتين أصبت في ساقي، وبقيت ستة أشهر بدون لعب.", "Two years ago I injured my leg, and I stayed six months without playing."),
    ("كانت فترة صعبة، لكنها علمتني الكثير.", "It was a hard period, but it taught me a lot."),
    ("وما حلمك الآن؟", "And what is your dream now?"),
    ("أن ألعب مع فريق بلدي، وأن أفتح مدرسة لكرة القدم للأطفال الفقراء في حينا.",
     "To play for my country's team, and to open a football school for poor children in my neighbourhood."),
], q=[
    ("mc", "أين بدأ ياسر يلعب كرة القدم؟", "Where did Yasser start playing football?",
     ["أمام بيته", "في المدرسة", "في ملعب كبير", "في العاصمة"], ["بدأ", "شارع"], 3),
    ("tf", "كان أبو ياسر لا يهتم بكرة القدم.", "Yasser's father was not interested in football.", False, ["تدريب"], 7),
    ("mc", "ماذا كان المدرب الأول يقول لياسر؟", "What did the first coach tell Yasser?",
     ["إن العمل أهم من الموهبة", "إن الموهبة تكفي", "إن عليه أن يترك الكرة", "إنه أفضل لاعب في الفريق"], ["مدرب", "موهبة"], 8),
    ("tf", "بقي ياسر نصف سنة بدون لعب بسبب إصابة.", "Yasser was out for half a year because of an injury.", True, ["ساق", "بدون"], 11),
]))

P.append(dict(title="حريق في السوق", names=[], s=[
    ("وقع حريق كبير صباح أمس في سوق الملابس في وسط المدينة.", "A big fire broke out yesterday morning in the clothes market in the city centre."),
    ("بدأ الحريق في دكان صغير في الساعة السادسة، قبل أن يفتح السوق.", "The fire started in a small shop at six o'clock, before the market opened."),
    ("وبسبب الريح القوية، انتقلت النار بسرعة إلى الدكاكين الأخرى.", "Because of the strong wind, the fire spread quickly to the other shops."),
    ("وصل رجال الدفاع المدني بعد عشر دقائق، واستمروا في العمل أكثر من ثلاث ساعات.",
     "Civil defence arrived ten minutes later, and kept working for more than three hours."),
    ("قالت الشرطة إن أحدا لم يمت، لكن ثلاثة رجال أصيبوا إصابات خفيفة، ونقلوا إلى المستشفى.",
     "Police said nobody died, but three men were slightly injured and taken to hospital."),
    ("دمرت النار أكثر من عشرين دكانا، وخسر أصحابها كل ما فيها.", "The fire destroyed more than twenty shops, and their owners lost everything in them."),
    ("قال أحد التجار إنه عمل في هذا السوق ثلاثين سنة، وإنه لا يعرف ماذا سيفعل الآن.",
     "One trader said he had worked in this market for thirty years, and he does not know what he will do now."),
    ("لم تعرف الشرطة بعد سبب الحريق، وبدأت تحقيقا.", "Police do not yet know the cause of the fire, and have opened an investigation."),
    ("لكن بعض التجار يقولون إن المشكلة في الكهرباء القديمة في السوق.", "But some traders say the problem is the market's old electricity."),
    ("ويضيفون أنهم طلبوا من المدينة إصلاحها منذ سنوات، لكن لم يحدث شيء.",
     "And they add that they asked the city to fix it years ago, but nothing happened."),
    ("وأعلنت الحكومة مساء أمس أنها ستساعد التجار ليعيدوا فتح دكاكينهم.",
     "Yesterday evening the government announced that it will help the traders reopen their shops."),
    ("وسيبقى السوق مغلقا حتى نهاية الشهر.", "The market will remain closed until the end of the month."),
], q=[
    ("mc", "متى بدأ الحريق؟", "When did the fire start?",
     ["قبل فتح السوق", "في منتصف النهار", "في المساء", "في الليل"], ["بدأ", "حريق"], 1),
    ("tf", "مات ثلاثة رجال في الحريق.", "Three men died in the fire.", False, ["مات", "رجل"], 4),
    ("mc", "ما سبب الحريق كما يقول بعض التجار؟", "What caused the fire, according to some traders?",
     ["كهرباء السوق القديمة", "طفل يلعب بالنار", "طعام على النار في دكان", "رجل مجنون"], ["كهرباء", "مشكلة"], 8),
    ("tf", "سيفتح السوق مرة أخرى بعد نهاية الشهر.", "The market will open again after the end of the month.", True, ["سوق", "مغلق"], 11),
]))

P.append(dict(title="السيارة الكهربائية", names=[], s=[
    ("في السنوات الأخيرة بدأت السيارات الكهربائية تظهر في شوارع مدننا.", "In recent years electric cars have started appearing on the streets of our cities."),
    ("هذه السيارات لا تحتاج إلى وقود، بل إلى كهرباء فقط.", "These cars don't need fuel, only electricity."),
    ("ولذلك فهي أفضل للهواء، وأقل صوتا.", "So they are better for the air, and quieter."),
    ("ويقول أصحابها إن الكهرباء في البيت أقل سعرا من الوقود بكثير.", "And their owners say electricity at home costs much less than fuel."),
    ("لكن هذه السيارات ليست مثالية.", "But these cars are not perfect."),
    ("أولا، سعرها ما زال عاليا، ولا يستطيع كل الناس أن يشتروها.", "First, their price is still high, and not everyone can buy them."),
    ("ثانيا، الأماكن التي تستطيع أن تأخذ منها الكهرباء قليلة خارج المدن الكبيرة.", "Second, places where you can get electricity are few outside the big cities."),
    ("ولذلك يخاف بعض الناس من السفر الطويل بها.", "So some people are afraid of long journeys in them."),
    ("ثالثا، يسأل بعض الخبراء: من أين تأتي الكهرباء نفسها؟", "Third, some experts ask: where does the electricity itself come from?"),
    ("إذا كانت تأتي من النفط، فالفائدة للبيئة أقل.", "If it comes from oil, the benefit to the environment is smaller."),
    ("رغم ذلك، تتوقع الحكومات أن تكون أكثر السيارات الجديدة كهربائية بعد عشرين سنة.",
     "Despite that, governments expect most new cars to be electric in twenty years."),
    ("وبعض الدول بدأت تعطي مالا لمن يشتري سيارة كهربائية.", "And some countries have started giving money to whoever buys an electric car."),
    ("أما أنا فأنتظر أن تصبح الأسعار أقل قبل أن أغير سيارتي القديمة.", "As for me, I am waiting for prices to become lower before I change my old car."),
], q=[
    ("tf", "السيارة الكهربائية تحتاج إلى وقود.", "The electric car needs fuel.", False, ["وقود"], 1),
    ("mc", "ماذا يقول أصحاب هذه السيارات عن الكهرباء في البيت؟", "What do the owners say about electricity at home?",
     ["إنه لا يكلف كثيرا", "إنه صعب جدا", "إنه يأخذ يوما كاملا", "إنه غير آمن"], ["بيت", "وقود"], 3),
    ("mc", "لماذا يخاف بعض الناس من السفر الطويل بهذه السيارات؟", "Why are some people afraid of long trips in these cars?",
     ["لأن أماكن الكهرباء قليلة خارج المدن", "لأنها بطيئة", "لأنها صغيرة", "لأن الطرق خارج المدن سيئة ولا يحبها الناس"], ["سفر", "خاف"], 7),
    ("tf", "ينتظر الكاتب أن تصبح الأسعار أقل.", "The writer is waiting for prices to become lower.", True, ["انتظر", "سعر"], 12),
]))

P.append(dict(title="ليلة في الصحراء", names=["نزار"], s=[
    ("لم أكن أتخيل أن الصحراء يمكن أن تكون جميلة إلى هذا الحد.", "I never imagined the desert could be so beautiful."),
    ("في الربيع الماضي نظم صديقي نزار رحلة لمجموعة صغيرة من الأصدقاء.", "Last spring my friend Nizar organised a trip for a small group of friends."),
    ("خرجنا من المدينة بعد الظهر في سيارتين كبيرتين.", "We left the city in the afternoon in two big cars."),
    ("بعد ساعتين اختفت الطرق والبيوت، ولم نعد نرى إلا الأرض والسماء.",
     "After two hours the roads and houses disappeared, and we saw nothing but land and sky."),
    ("قبل نهاية النهار وصلنا إلى مخيم صغير يديره رجل من المنطقة.", "Before the end of the day we reached a small camp run by a local man."),
    ("قدم لنا القهوة، وقال لنا أشياء كثيرة عن حياة الناس في الصحراء.",
     "He offered us coffee, and told us many things about people's lives in the desert."),
    ("قال إن الماء أهم شيء هناك، وإن له قيمة كبيرة.", "He said water is the most important thing there, and it has great value."),
    ("في المساء جلسنا حول النار وأكلنا لحما وخبزا ساخنا.", "In the evening we sat around the fire and ate meat and hot bread."),
    ("ثم أغلقنا الأضواء ونظرنا إلى السماء.", "Then we turned off the lights and looked at the sky."),
    ("لم أر في حياتي هذا العدد من النجوم.", "I had never in my life seen so many stars."),
    ("كان الهدوء كاملا، ولم نسمع إلا صوت الريح.", "The silence was complete, and we heard only the sound of the wind."),
    ("الليل كان باردا جدا، رغم أن النهار كان حارا.", "The night was very cold, even though the day was hot."),
    ("في الصباح عدنا إلى المدينة، لكن جزءا مني بقي هناك.", "In the morning we returned to the city, but a part of me stayed there."),
], q=[
    ("mc", "من نظم الرحلة؟", "Who organised the trip?",
     ["صديق الكاتب", "رجل من الصحراء", "شركة سفر", "الكاتب نفسه"], ["نظم", "رحلة"], 1),
    ("tf", "وصل الأصدقاء إلى المخيم في الليل.", "The friends reached the camp at night.", False, ["مخيم", "وصل"], 4),
    ("mc", "ماذا قال الرجل عن الماء؟", "What did the man say about water?",
     ["إنه أهم شيء في الصحراء", "إنه كثير جدا تحت الأرض هناك", "إنه لا يحتاج إليه", "إنه رخيص"], ["ماء", "قيمة"], 6),
    ("tf", "كانت الليلة في الصحراء باردة.", "The night in the desert was cold.", True, ["ليل", "بارد"], 11),
]))

P.append(dict(title="قبل أن تسافر", names=[], s=[
    ("السفر إلى بلد جديد تجربة رائعة، لكنه يحتاج إلى استعداد.", "Travelling to a new country is a wonderful experience, but it needs preparation."),
    ("إليك بعض الأشياء التي يجب أن تفكر فيها قبل أن تسافر.", "Here are some things you should think about before you travel."),
    ("أولا، تأكد أن أوراقك كاملة، وأن أوراق السفر لن تنتهي أثناء الرحلة.",
     "First, make sure your papers are complete, and that your travel documents will not expire during the trip."),
    ("ثانيا، اقرأ عن البلد الذي تذهب إليه: عن طقسه وعاداته وأكله.", "Second, read about the country you are going to: its weather, customs and food."),
    ("في بعض البلاد هناك ملابس خاصة لأماكن محددة، وفي بلاد أخرى لا يأكل الناس في الشارع.",
     "In some countries there are special clothes for certain places, and in others people don't eat in the street."),
    ("ثالثا، تعلم بعض الكلمات البسيطة في لغة البلد، مثل مرحبا وشكرا ومن فضلك.",
     "Third, learn a few simple words in the country's language, like hello, thank you and please."),
    ("الناس يحبون الضيف الذي يحاول أن يتكلم لغتهم، حتى إذا لم يكن كلامه صحيحا.", "People like a guest who tries to speak their language, even if what he says is not correct."),
    ("رابعا، لا تضع المال كله في مكان واحد.", "Fourth, don't put all the money in one place."),
    ("احتفظ ببعض المال في الحقيبة، وبعضه في جيبك.", "Keep some money in the bag, and some in your pocket."),
    ("خامسا، اكتب أرقام الهواتف المهمة على ورقة، لأن الهاتف قد يضيع.", "Fifth, write important phone numbers on a piece of paper, because the phone may get lost."),
    ("وأخيرا، لا تحاول أن ترى كل شيء في أيام قليلة.", "Finally, don't try to see everything in a few days."),
    ("اجلس في مطعم صغير، وانظر إلى الناس، واستمتع بالرحلة.", "Sit in a small restaurant, watch the people, and enjoy the trip."),
], q=[
    ("tf", "يقول النص إن السفر لا يحتاج إلى استعداد.", "The text says travel needs no preparation.", False, ["سفر", "استعداد"], 0),
    ("mc", "لماذا يجب أن تتعلم بعض الكلمات في لغة البلد؟", "Why should you learn some words in the country's language?",
     ["لأن الناس يحبون من يحاول", "لأنها سهلة", "لأن الفنادق تطلب ذلك", "لأن الشرطة تسأل الناس عن ذلك"], ["أحب", "حاول"], 6),
    ("mc", "أين يجب أن تضع مالك؟", "Where should you put your money?",
     ["في أكثر من مكان", "في الحقيبة فقط", "في الفندق", "في جيبك فقط"], ["مال", "مكان"], 7),
    ("tf", "يقول الكاتب إن عليك أن تكتب الأرقام المهمة على ورقة.", "The writer says you should write important numbers on paper.", True, ["رقم", "ورقة"], 9),
]))

P.append(dict(title="المفتاح", names=["هالة"], s=[
    ("عادت هالة من عملها متأخرة، وكانت تريد أن تنام بسرعة.", "Hala came home from work late, and she wanted to sleep quickly."),
    ("وقفت أمام باب شقتها وبحثت في حقيبتها عن المفتاح، لكنها لم تجده.",
     "She stood in front of her flat's door and looked in her bag for the key, but she didn't find it."),
    ("بحثت مرة ثانية وثالثة، ثم أخرجت كل ما في الحقيبة على الأرض.", "She looked a second and third time, then took everything out of the bag onto the floor."),
    ("لا مفتاح.", "No key."),
    ("تذكرت أنها وضعته على مكتبها في العمل عندما كانت تتكلم على الهاتف.",
     "She remembered that she had put it on her desk at work while she was talking on the phone."),
    ("كانت الساعة 11 في الليل، والمكتب مغلق.", "It was 11 at night, and the office was closed."),
    ("اتصلت بأختها، لكنها كانت في بلد آخر.", "She called her sister, but she was in another country."),
    ("جلست أمام الباب وهي لا تعرف ماذا تفعل، وكانت خائفة قليلا.", "She sat in front of the door not knowing what to do, and she was a little afraid."),
    ("فجأة فتح باب الشقة المقابلة، وخرجت منها جارتها العجوز.", "Suddenly the door of the flat opposite opened, and her old neighbour came out."),
    ("قالت لها: يا ابنتي، لماذا تجلسين هنا؟", "She said to her: My daughter, why are you sitting here?"),
    ("شرحت هالة المشكلة، فضحكت الجارة ودخلت شقتها.", "Hala explained the problem, and the neighbour laughed and went into her flat."),
    ("بعد دقيقة عادت وفي يدها مفتاح.", "A minute later she came back with a key in her hand."),
    ("قالت: أعطتني أمك هذا المفتاح قبل سنتين، وقالت لي: ستحتاجه هالة يوما ما.",
     "She said: Your mother gave me this key two years ago, and said to me: Hala will need it one day."),
], q=[
    ("mc", "أين كان المفتاح؟", "Where was the key?",
     ["في مكتب العمل", "في الحقيبة", "عند أختها", "في السيارة"], ["مكتب", "وضع"], 4),
    ("tf", "كانت أخت هالة في البيت تلك الليلة.", "Hala's sister was at home that night.", False, ["أخت"], 6),
    ("mc", "من ساعد هالة؟", "Who helped Hala?",
     ["جارتها", "أختها", "مديرها", "رجل الشرطة"], ["جار"], 8),
    ("tf", "كان المفتاح عند الجارة منذ سنتين.", "The neighbour had had the key for two years.", True, ["مفتاح", "سنة"], 12),
    ("mc", "من أعطى الجارة المفتاح؟", "Who gave the neighbour the key?",
     ["أم هالة", "هالة", "أخت هالة", "صاحب الشقة"], ["أعطى", "أم"], 12),
]))

P.append(dict(title="المدينة أم القرية؟", names=[], s=[
    ("كل سنة يترك آلاف الشباب قراهم ويذهبون إلى المدن الكبيرة.", "Every year thousands of young people leave their villages and go to the big cities."),
    ("هم يبحثون عن عمل أفضل، وعن جامعات، وعن حياة أكثر حركة.", "They are looking for better jobs, universities, and a more active life."),
    ("وفي المدينة يجدون فعلا فرصا كثيرة لا يجدونها في القرية.", "And in the city they do find many opportunities they can't find in the village."),
    ("لكن الحياة في المدينة لها ثمن.", "But life in the city has a price."),
    ("السكن غال، والطرق مليئة بالسيارات، والهواء ليس نظيفا.", "Housing is expensive, the roads are full of cars, and the air is not clean."),
    ("وكثير من الناس يعيشون سنوات في مبنى واحد ولا يعرفون جيرانهم.", "And many people live for years in one building without knowing their neighbours."),
    ("أما في القرية، فالحياة بسيطة وهادئة.", "In the village, though, life is simple and quiet."),
    ("الناس يعرفون بعضهم، ويساعدون بعضهم في الأوقات الصعبة.", "People know each other, and help each other in hard times."),
    ("لكن الخدمات قليلة، والمستشفى قد يكون بعيدا ساعة أو أكثر.", "But services are few, and the hospital may be an hour or more away."),
    ("في السنوات الأخيرة ظهر شيء جديد: بعض الناس بدؤوا يعودون إلى القرى.",
     "In recent years something new has appeared: some people have started going back to the villages."),
    ("بفضل الإنترنت يستطيعون أن يعملوا من هناك لشركات في المدينة.", "Thanks to the internet they can work from there for companies in the city."),
    ("ربما يكون المستقبل بين الاثنين: عمل المدينة وهدوء القرية.", "Perhaps the future lies between the two: city work and village calm."),
], q=[
    ("mc", "لماذا يذهب الشباب إلى المدن؟", "Why do young people go to the cities?",
     ["للبحث عن عمل ودراسة", "لأن السكن رخيص", "لأن الهواء نظيف", "لأنهم يعرفون الجيران"], ["بحث", "عمل"], 1),
    ("tf", "السكن في المدينة رخيص.", "Housing in the city is cheap.", False, ["سكن", "غال"], 4),
    ("mc", "ما المشكلة في القرية كما يقول النص؟", "What is the problem in the village, according to the text?",
     ["ليس فيها خدمات كثيرة", "الناس لا يعرفون بعضهم", "الهواء ليس نظيفا", "الطرق مليئة بالسيارات"], ["خدمة"], 8),
    ("tf", "بعض الناس يعملون من القرية لشركات في المدينة.", "Some people work from the village for companies in the city.", True, ["شركة", "إنترنت"], 10),
]))

P.append(dict(title="قصة القهوة", names=["اليمن", "مكة", "القاهرة", "أوروبا", "أفريقيا", "إسطنبول"], s=[
    ("يشرب الناس في العالم اليوم ملايين الأكواب من القهوة كل ساعة.", "People around the world today drink millions of cups of coffee every hour."),
    ("لكن قليلين يعرفون أن قصة القهوة بدأت في منطقتنا.", "But few know that the story of coffee began in our region."),
    ("تقول القصص القديمة إن القهوة جاءت من أفريقيا، ثم وصلت إلى اليمن قبل أكثر من 500 سنة.",
     "Old stories say coffee came from Africa, then reached Yemen more than 500 years ago."),
    ("هناك بدأ الناس يشربونها ليبقوا بدون نوم أثناء الصلاة في الليل.", "There people began drinking it to stay without sleep during prayers at night."),
    ("ومن اليمن انتقلت القهوة إلى مكة والقاهرة ثم إلى إسطنبول.", "From Yemen coffee moved to Mecca and Cairo, then to Istanbul."),
    ("وفي هذه المدن فتحت أول بيوت القهوة، وأصبحت مكانا يلتقي فيه الناس ليتكلموا ويلعبوا ويسمعوا القصص.",
     "In these cities the first coffee houses opened, and they became a place where people met to talk, play and listen to stories."),
    ("لم يكن الجميع سعداء بذلك.", "Not everyone was happy with that."),
    ("بعض الملوك أغلقوا بيوت القهوة، لأنهم ظنوا أن الناس يتكلمون فيها عن السياسة.",
     "Some kings closed the coffee houses, because they thought people talked politics in them."),
    ("لكن الناس لم يتركوا القهوة، وعادت البيوت تفتح من جديد.", "But people didn't give up coffee, and the houses opened again."),
    ("بعد ذلك وصلت القهوة إلى أوروبا، ومن هناك إلى كل العالم.", "After that coffee reached Europe, and from there the whole world."),
    ("اليوم للقهوة العربية مكان خاص في ثقافتنا.", "Today Arabic coffee has a special place in our culture."),
    ("نقدمها للضيف قبل كل شيء، وهي عندنا علامة على الاحترام.",
     "We offer it to the guest before anything else, and for us it is a sign of respect."),
], q=[
    ("mc", "إلى أين وصلت القهوة من أفريقيا؟", "Where did coffee go from Africa?",
     ["إلى اليمن", "إلى القاهرة", "إلى أوروبا", "إلى مكة"], ["وصل"], 2),
    ("tf", "كان الناس في اليمن يشربون القهوة لينام الناس جيدا.", "People in Yemen drank coffee to sleep well.", False, ["شرب", "صلاة"], 3),
    ("mc", "لماذا أغلق بعض الملوك بيوت القهوة؟", "Why did some kings close the coffee houses?",
     ["خافوا من الكلام في السياسة", "لأن القهوة كانت غالية", "لأن الناس كانوا ينامون فيها", "لأنها كانت قديمة"], ["أغلق", "سياسة"], 7),
    ("tf", "القهوة العربية لها مكان مهم في الثقافة اليوم.", "Arabic coffee has an important place in the culture today.", True, ["ثقافة", "خاص"], 10),
]))

P.append(dict(title="يوم لتنظيف الشاطئ", names=["رامي"], s=[
    ("في يوم السبت الماضي اجتمع أكثر من مئة شخص على شاطئ المدينة، لا للسباحة، بل للتنظيف.",
     "Last Saturday more than a hundred people gathered on the city beach, not for swimming, but for cleaning."),
    ("الفكرة جاءت من شاب اسمه رامي، يعمل معلما في مدرسة قريبة.", "The idea came from a young man called Rami, who works as a teacher at a nearby school."),
    ("قال رامي إنه كان يمشي على الشاطئ كل صباح، وكان يحزن عندما يرى أن الشاطئ ليس نظيفا.",
     "Rami said he used to walk on the beach every morning, and it saddened him to see that the beach was not clean."),
    ("فكتب رسالة على الإنترنت يطلب فيها من الناس أن يأتوا ويساعدوا.", "So he wrote a message online asking people to come and help."),
    ("لم يتوقع أن يأتي أكثر من عشرين شخصا، لكن العدد كان أكبر بكثير.",
     "He didn't expect more than twenty people to come, but the number was much bigger."),
    ("جاء طلاب ومعلمون وعائلات مع أطفالهم، وحتى بعض الرجال من الميناء.", "Students, teachers, families with their children, and even some men from the port came."),
    ("عملوا من الساعة 7 حتى الظهر، وجمعوا أشياء كثيرة جدا.",
     "They worked from 7 until noon, and collected a great many things."),
    ("وجدوا أحذية قديمة وملابس، وحتى كرسيا قديما.", "They found old shoes and clothes, and even an old chair."),
    ("قالت امرأة جاءت مع ابنتيها إنها تريد أن تعلم أطفالها أن الشاطئ للجميع، وأن علينا جميعا أن نهتم به.",
     "A woman who came with her two daughters said she wants to teach her children that the beach belongs to everyone, and we must all look after it."),
    ("بعد نجاح اليوم الأول، قرر رامي أن ينظم يوما مثله في أول يوم سبت من كل شهر.",
     "After the success of the first day, Rami decided to organise a day like it on the first Saturday of every month."),
    ("وقالت المدينة إنها ستضع صناديق أكثر على الشاطئ.", "And the city said it would put more bins on the beach."),
], q=[
    ("mc", "من صاحب الفكرة؟", "Whose idea was it?",
     ["معلم شاب", "مدير المدرسة", "امرأة مع ابنتيها", "رجل من الميناء"], ["فكرة"], 1),
    ("tf", "جاء إلى الشاطئ عشرون شخصا فقط.", "Only twenty people came to the beach.", False, ["شخص"], 4),
    ("mc", "كم مرة سينظم رامي هذا اليوم؟", "How often will Rami organise this day?",
     ["مرة كل شهر", "كل يوم سبت", "مرة في السنة", "مرة في الأسبوع"], ["نظم", "شهر"], 9),
    ("tf", "ستضع المدينة صناديق جديدة على الشاطئ.", "The city will put new bins on the beach.", True, ["صندوق", "شاطئ"], 10),
]))
